### ISSUE TITLE
Keyword parameter <GEO> not allowed in call to: WRITE_TIFF

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1058]
Any chance to implement the keyword parameter <GEO> to the write_tiff procedure?

**Comment by slayoo** [comment]
@rexso? thanks, Sylwester

**Comment by brandy125** [comment]
If it is possible implement as well the /float keyword parameter

**Comment by rexso** [comment]
Hi. Sorry for my belated reply.

Due to lack of time, I have not really touched GDL since I changed employer, unfortunately. I would like to contribute when possible, but unfortunately I have no time to look into this the coming week.

Currently WRITE_TIFF is supported through the generic WRITE_IMAGE routine, whereas writing through libtiff would be necessary for geotiff write support. This issue is related to #121 and further mentioned in #288.

Implementing /FLOAT should not be too hard when the fundamentals are in place.

I will see what I can do in September, if the issue is still open then.

**Comment by brandy125** [comment]
Hi,

perfect!

Thanks!

**Comment by brandy125** [comment]
Hi @rexso, hi @slayoo ,

any news on write_tiff with /geotiff and /float support?

working with geotiffs is coming more and more. I think it is very important to have this feature.

**Comment by brandy125** [comment]
Just wanted to ask again someone is working on the /geotiff and /float keywords.

**Comment by slayoo** [comment]
@brandy125, @rexso had been the only developer working on these features, and we have not heard back from him recently. No news here. 

@gnudatalanguage/gdlteam, any volunteers to look at these two missing features? (`/geotiff` and `/float` support in `write_tiff`). Thanks.

**Comment by rexso** [comment]
Sorry for my late reply. Unfortunately, due to some long lasting personal problems, I do not have the capacity to work on this implementation right now. I would very much like to do further contributions to the GDL project, but I cannot make any promises at this point. I realise that this is not the answer you were looking for, and i sincerely apologise. I will come back to this tread to let you know when I start working on the implementation. Hopefully I will be able to make myself more useful soon, but for now, this issue is open if someone else want to make an attempt.

Again, I am so sorry for my late reply and for not being able to work on the implementation yet. I appreciate your patience though, and hope for your understanding.

**Comment by alaingdl** [comment]
@rexso I hope your problems will be solved.

In a project like GDL, it is very classical to give hand-over to others. When a clear interest is express on a given functionality, we can consider to spend some time on it, or to have a student on it. I found it is very valuable for students to spend time to add  functionalities in GDL. If you can list the most urgent functionalities & keywords, it is valuable. Examples of _snippets_ are also very useful.

**Comment by slayoo** [comment]
Take care, @rexso, completely no need to apologize!

**Comment by slayoo** [comment]
@brandy125 It would also be helpful to have a test routine depicting the missing functionality - best a test that works in IDL and fails in GDL as of now.

**Comment by brandy125** [comment]
@slayoo here is the test routine for checking the keyword /float and geotiff=geotiff:

```
pro test_write_tiff

        catch, error
        if (error ne 0) then begin
            print, "ERROR: ", error
            print, "Message: ", !ERROR_STATE.MSG
            error=0
            exit,status=1
        endif

        image=dist(10)

        ;test for keyword geotiff
        write_tiff,'image.tif',image,geotiff=geotiff

        ;test for keyword /float
        write_tiff,'image.tif',image,/float

end
```
Could you please include it to the testsuite folder and add the program in the file LIST?

Output of "make test":

The following tests FAILED:
        198 - test_write_tiff.pro (Failed)

Output of log file:

ERROR:           -1
Message: WRITE_TIFF: Keyword parameter <GEOTIFF> not allowed in call to: WRITE_TIFF

<end of output>
Test time =   0.11 sec
----------------------------------------------------------
Test Failed.
"test_write_tiff.pro" end time: Apr 21 14:27 -03
"test_write_tiff.pro" time elapsed: 00:00:00
----------------------------------------------------------


In IDL the program runs without error message.

[test_write_tiff.pro.zip](https://github.com/gnudatalanguage/gdl/files/8533678/test_write_tiff.pro.zip)

**Comment by brandy125** [comment]
In the file INSTALL.CMake is written:

$ make -j 3

For other systems, a native project file will be produced.

To launch the tests, run:
$ make check

To install, type:
$ make install



But it does not find it:

bash$ make check
make: *** No rule to make target 'check'.  Stop.
bash$ 


Am I doing anything wrong?

**Comment by slayoo** [comment]
Fixed: https://github.com/gnudatalanguage/gdl/commit/c13fda894a5375db9bae46998ecc2f4610b633a2
Thank you!

**Comment by SkippySky** [comment]
Hi Guys,

 

I notice that I’m getting cc’d on a lot of gnudata emails.

 

I’m not a Developer in your sense of eh word, but just a high level dabbler in IDL/GDL.

 

Haven’t used C since the VAX was King of the World… 😉

 

Please feel free to drop my name from the cc list…

 

 

Regards,

 

Andrew

**Comment by slayoo** [comment]
@SkippySky sorry, my bad. Indeed, the "gdlteam" group is meant for GDL users & super low-volume announcements.
I will create a separate "gdldevs" group for such messages. Apologies.

**Comment by SkippySky** [comment]
Goodness – does that mean I’m the only GDL user…. ;-)

 

A.

**Comment by brandy125** [comment]
Sure, I will work on that!

**Comment by brandy125** [comment]
Any news about missing /geo and /float keywords in write_tiff?

I would really appreciate if someone could work on that.

Thanks!

**Comment by brandy125** [comment]
Hi guys, any news here? Someone working on that?

**Comment by GillesDuvert** [comment]
@brandy125 look at #1525
