### ISSUE TITLE
read_anygraphicsfilewithmagick should not convert to bytes by default

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1117]
While looking at the code to try to locate which call was actually causing the segfault referenced in issue #1101 , I saw that `read_anygraphicsfilewithmagick` has an automatic conversion of 16-bit images to bytes. 

This seems to be:
a) At odds with IDL's behaviour of returning the image in whatever format is in the original file.
b) Undesirable, as the user may wish to do things other than display the image in (e.g. a 16 bit jpeg2000).

I suggest therefore removing the conversion, or making it an option enabled by a flag for cases where it may be necessary.

**Comment by GillesDuvert** [comment]
Actually, `read_anygraphicsfilewithmagick` just uses `magick_read()` so the culprit is in or below ` magick_read()`.
 I never got a version of ImageMagick that could handles 16bit images, and in general this will be a problem as the distributions do not necessary ship such 16-bits enabled image magick. I would have expected GDL to do as well as IDL and that a 16bit aware imagemagick give back a short int image instead of a byte image in ` magick_read()` as  
this is explicitly wtritten in the code: if the (magick library) returned image.depth is 16 then the GDL user will get an INT image, not a BYTE.
Probably nobody tested it for lack of 16 bit compliant imagemagick.
Are you sure that your imagemagick library handles 16 bit images (not speaking of TIFF images that do not use imagemagick)?

**Comment by jtappin** [comment]
I'm using graphicksmagick rather than ImageMagick, at first sight `gm` does appear to handle 16bit, but I'll need to check to see if it really works as it should.

**Comment by jtappin** [comment]
Just done a few quick tests on IM and GM with this 16-bit png (generated by gimp):
![test16](https://user-images.githubusercontent.com/658624/132840198-fb58ed82-63cc-48e9-b97e-403974bda84b.png)
````
magick convert test16.png -depth 16 test16m.rgb
gm convert test16.png -depth 16 -endian native test16.rgb
````
both generate files that appear sensible when read into GDL with a simple `readu` into a `uint` array of dimensions `[3, 120, 100]`. GM does need the `-endian native` option otherwise it produces a byte-swapped image. 
Whether that means that every 16-bit image is handled correctly is of course another matter.

**Comment by GillesDuvert** [comment]
works now (provided one has a 16 bit aware graphcismagick)
