### ISSUE TITLE
OPLOT does not honour !Y

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1213]
I guess in some ways this is a bit of an odd one, in that GDL appears to be doing what IDL **says** it does rather than what it actually does.

In graffer, I have for many years used `oplot` in conjunction with saving the `!y` system variable to allow traces  to be plotted on two different Y-axes. However now in GDL `oplot` appears to use the coordinate system established by the most recent call to `plot` rather than the current value of `!y`, I'm not sure whether this is a recent change though I think it may be as I'm sure I have used graffer in GDL with plots with two Y-axes. `plots` on the other hand continues to use the plot transform established by `!y`. Also `axis` seems to be getting thoroughly confused with logarithmic axes.

This example code attempts to illustrate the effects in a reasonably simple manner.
[haxis.pro](https://github.com/gnudatalanguage/gdl/files/7594476/haxis.txt)

The attached screenshots are for `haxis, [1,0]
In GDL
![haxisg10](https://user-images.githubusercontent.com/658624/143214250-b34b9cdf-0779-4568-b98d-06d2e1a5266c.png)
In IDL
![idl](https://user-images.githubusercontent.com/658624/143211041-959ab02f-60ae-4507-8e83-c74b1e0c329b.png)

Interestingly what GDL does is what the IDL documentation claims to do, although since at least 2011 `oplot` has  followed `!y`.

**Comment by jtappin** [comment]
Quick additional note.
`contour, /overplot` does follow `!y`

**Comment by GillesDuvert** [comment]
@jtappin you said "Interestingly what GDL does is what the IDL documentation claims to do, although since at least 2011 oplot has followed !y." 
This explains the confusion --- some contributors trying to do it by the book, the others by example...
a little like !P.SYMSIZE that is honored by GDL but not by IDL...

thanks for the example, but I remember having seen issues when a projection is active, will come back later on thi subject.

**Comment by GillesDuvert** [comment]
Should be OK since #1320, at least for OPLOT (AXIS has been improved, too).
The graphic code using plplot, a synchronisation beween the plplot setup and !X, !Y and !P is not insured for all cases and all graphic commands, making GDL insecure wrt the saving/restoring of direct graphic system variables.
