### ISSUE TITLE
error: % SET_PLOT: Device not supported/unknown: X in approx. 1% of cases

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1226]
when running approx. 100 gdl processing programs in parallel  (on a 80 CPU machine)
I get in approx. 1% of cases the error message:

% SET_PLOT: Device not supported/unknown: X

when executing the commands:

```
GDL>set_plot,'z'
GDL>set_plot,'x'
```

I will try to reproduce the problem with a simpler test program.
Here my setup:

GDL> print,!gdl
{ 1.0.1 Git Dec  6 2021  1638759600   1   1   1}

on

#1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)

**Comment by brandy125** [comment]
I replaced

```
GDL>set_plot,'z'
GDL>plot,findgen(100)
GDL>image=tvrd()
GDL>set_plot,'x'
```

with

```
GDL>window,/free
GDL>plot,findgen(100)
GDL>image=tvrd()
```

and now I get in approx. 1% of cases the following error message:

; % WINDOW: Routine is not defined for current graphics device.


Why only in 1% of the cases?
How can it be that "window" is not defined or that "set_plot" is not supported?
How to debug further?

I am running this processing jobs since one year with the version { 1.0.0-rc.3 git Aug 28 2020  1598583600   1   0   1}
and never had this problem. Now with the new version it happens.

**Comment by GillesDuvert** [comment]
hi @brandy125 
This is an unexpected bug!
Aug 28 2020 is before GDL switched, mainly for simpler compatibility with macOS and Windows, to plot windows made with the wxWidgets driver of plplot. The name 'x' is still the same (any other name would have confused existing IDL programs).
The message "`WINDOW: Routine is not defined for current graphics device`" is issued if the current device has no windows, i.e., like if you do `window/free` when the device is still` 'z'` (or at least not 'x')
... this is going to be tough if there are race problems, normally all those programs are independent...
The first error `SET_PLOT: Device not supported/unknown: X` is even weirder, i suppose that a list of available graphic devices was printed just before this message, what are they?
 
As it may be due to some schizophrenic behaviour of GDL, could you try with  a GDL compiled with both X11 (-DX11) and wxWidgets, (or even without wxwidgets at all, if you do not need to use, eh, widgets). Then the 'X' device will be the very same X11 device as before. To enable the X11 and not wxWidget 'window', you either set the env. var `GDL_DISABLE_WX_PLOTS` (to anything) or call gdl with the `--no-use-wx `switch.

**Comment by brandy125** [comment]
> i suppose that a list of available graphic devices was printed just before this message, what are they?
> 
> 

nothing was printed, just this line.

I will try your suggestions and keep you informed...

**Comment by brandy125** [comment]
I think I found the error, was my mistake.

when I installed the new GDL, I did as well a change in my code. I exchanged “nohup command” with “setsid nohup command”. This seems to need much more X resources since it is supposed to open a new shell for each command.
What is happening is actually that the maximum number of clients is reached on my machine (supposed to be 1024) so it was not able to open any window any more.

So when I start GDL now in a normal shell I get:

>gdl
Maximum number of clients reached12:51:14: Error: Unable to initialize GTK+, is DISPLAY set properly?
WARNING: wxWidgets not initializing
Maximum number of clients reachedInvalid MIT-MAGIC-COOKIE-1 key  GDL - GNU Data Language, Version 1.0.0-rc.3 git

I tested now with the version from last year and same behaviour, so nothing to worry.

Sorry!
