### ISSUE TITLE
Where are the ugly, but functional, postscript fonts ;)

### ISSUE THREAD

**Issue by dirteat** [gnudatalanguage/gdl#1306]
Hi there,
it seems the default postscript device output fonts have been changed from the "typical" ugly aliased one to something looking nice.

I have a problem with this for various reasons :)

1) The new fonts are not fully functional, this piece of code does not display properly the Greek letter "epsilon". It looks like it is replaced by a white space (other Greek letters are correctly displayed, even though I did not test the whole alphabet).

```
set_plot,'ps'
fileout='test.eps'
device,filename=fileout,/color,bits=8
plot,[0,1],[0,1],ytitle='!7e!6!D1!N'
device,/close
end
```

2) For matching historical figures, I would like to use the ugly font, on purpose. I've tried various things on the command line, but only the nice looking ones show up. Using:

`gdl --no-use-wx`

I still see this message:
- Using WxWidgets as graphics library (windows and widgets)

Any help welcome, thanks!

This is gdl-1.0.1, but the same problem is present in gdl-1.0.0

**Comment by GillesDuvert** [comment]
Hi @dirteat  I can reproduce your error in GDL-1.0.0
Somewhere around 0.8 the default font for PostScript has been forced to nice PostScript fonts instead of ugly Hershey 'fonts'. It was expected (and checked, at the time) that plplot (that writes the postscript file behind the scenes) would know how to write greek etc letters. Apparently, this is no more the case (?). 
There are two solutions.
The first would be to change line 110 in src/deviceps.hpp as follows:
`      string what="text=0,color="+i2s(color);` and recompile
to get back the ugly fonts.
The second is to install the current GDL version since it is more flexible with the fonts and uses hershey by default.

For the record, Hershey fonts are not ugly at all, it is just that plplot does not "pixelise" them correctly, at least with its basic drivers used in GDL.

**Comment by GillesDuvert** [comment]
Although the problem is not corrected (plplot driver + postscript fonts) I believe the default hershey fonts with #1338 changes give more than acceptable results:
![image](https://user-images.githubusercontent.com/33936193/178161034-e455b1dc-2635-4333-882f-a72ed0d43b1c.png)

**Comment by dirteat** [comment]
Yes, I forgot to update, but whatever fonts are now, they look as the historical ones (gdl-1.0.2)!

Big thanks!
