### ISSUE TITLE
RDPIX should work even if no previously opened window

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1391]
In IDL, when no window, a call to RDPIX does open one then work

In GDL, we have : 

```
GDL> rdpix, dist(123)
% Compiled module: RDPIX.
% Compiled module: DIST.
Press left or center mouse button for new output line."
... right mouse button to exit.
17:03:59: Debug: ClientToScreen cannot work when toplevel window is not shown
17:03:59: Debug: ClientToScreen cannot work when toplevel window is not shown
17:03:59: Debug: ClientToScreen cannot work when toplevel window is not shown
```

Maybe just adding a test on !d.window and open a new one if below 0 ?

A.

**Comment by GillesDuvert** [comment]
rdpix does not seem to work OK for IDL too. (not showing the dist() image , no position written) ??
gdl --no-use-wx (so with X11) is equal to IDL 
with wxWidgets, there may be an issue due to the delay the first window appears. Related to the difficulty of having wxWidgets eventloop staring in the frist place.

**Comment by GillesDuvert** [comment]
works for me (last version)
