### ISSUE TITLE
Brew in real life : maybe preparing a formula ?!

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1409]
I have few colleagues using GDL on a daily basis and working on OSX.
I help them by installing and maintaining GDL. 

Time to time they have to add an app. or upgrade Brew.

The result today was to loose GDL because version of gsl has changed.
Last time, few weeks ago, it was another lib.

then I have to recompile from the script ...

Just to say in the context of Brew the script is not a definitive answer and maybe we will have to provide or to maintain a formula to Brew.

Despite being based on old version of GDL, Macport provides a working version of GDL with less _glitches_ to my knowledge.

Let's be clear, I have no opinion on Brew or Port, I just found the upgrade process of Mac is really problematic, pressing the end-users to move to newer major versions and broken lots of "local" softs. The location of some major libs. is changing too frequently.

**Comment by GillesDuvert** [comment]
For sure. GDL has too many dependencies, and build_gdl.sh relying on the precise name of a particular package in a precise distribution (homebrew for macOSX, but this is true for linux distros too) is nightmarish.
OTHO, provided the needed libraries have been installed, the current CMAKE, despite all its dumbness, works well.

The difficulty lies in 'the needed libraries'. Because we depend on xdr, which is found in oodles of system libraries, most of them not providing what we need. Same for the readline library. There is also the absence of choice between imagemagick and graphicsmagick, which is painful, the fact that these libraries support or not 16 bit images... Plplot is not good either, as it comes in many different flavors, depending on the packager whimses. Not speaking of the python nighmare, but that is true for all user of python.

I do not see any general way to solve this, and yes, all those petty problems take all of our time. However, here some suggestions:

For OSX and Windows, we have worked, and that is the purpose of build_gdl.sh, to create installers. The installer works on windows, and should work on OSX although I do not know about #1074 status (should we merge it? does it make a DMG?). Providing an installer is THE answer for  your reported OSX (and Windows) problems. The installer is made by build_gdl.sh, using the libraries known, and maintained, by us, and installed GDLs should work on every 'normal' user machines, without need to recompile GDL. Looks to me that is the case for Windows, and I do not see why we could not provide the same on OSX. The WIKI documentation should be written accordingly (i.e., cmake build procedure removed from the Window and OSX wiki pages and reported to another special page).

In all the other cases (I see two: linux in general and OSX for special cases, like your need of X11 on an OSX server) we **should not advertize the use of build_gdl.sh** and ask people to follow the recipes of [Way 2, using cmake](https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Linux#cmake) on our WIKI . The only information needed at this point is an accurate list of package names needed for the building of GDL. This list is more or less the one in build_gdl.sh, it should be maintained on one special WIKI page, and that can be done by anybody using PRs.

Or, we put all our eggs in build_gdl.sh, but it will need constant updates by somebody efficient in shell language.

**Comment by GillesDuvert** [comment]
most of the comments here are obsolete now.
