### ISSUE TITLE
Critical bug in basic plot

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1415]
This tricky bug does exist in all versions I tested till 0.9.9. 

(another bug report on yrange no more enforced will be issued ASAP !) 

What is good
```
plot, shift(fft(80*sin(findgen(8000)/100*!dpi)), 4000), yrange=[-.001, .001]
oplot, shift(imaginary(fft(80*sin(findgen(8000)/100*!dpi))), 4000)
```
(you can see the "lines" (one positive, one negative) around 4000

What is bad 1 (no yrange)
```
plot, shift(fft(80*sin(findgen(8000)/100*!dpi)), 4000)
oplot, shift(imaginary(fft(80*sin(findgen(8000)/100*!dpi))), 4000)
```

What is bad 2 (with yrange)
```
plot, shift(fft(80*sin(findgen(8000)/100*!dpi)), 4000), yrange=[-.00001, .00001]
oplot, shift(imaginary(fft(80*sin(findgen(8000)/100*!dpi))), 4000)
```

**Comment by GillesDuvert** [comment]
excellent! nice bug!

**Comment by GillesDuvert** [comment]
Actually, plplot seem to refuse to plot very steep lines. Probably because the plot positions are internally converted to short ints by plplot (but long ints would make a limit also).
This is very annoying, the fact that it was not reported before is somewhat of a relief.
We are in a position to prevent this bug by scaling the offending values but this will slow all plotting commands.

**Comment by GillesDuvert** [comment]
simple oneliner patch for yet another plplot limitation.
