### ISSUE TITLE
quality of the plots after pr 1407

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1419]
I compile GDL *with the script* on 3 machines : u2204 (local), Deb10 (remote), OSX12 (remote)

- this test fails : 101 - test_hdf5.pro (Failed)
- four buttons are back for the wx driver 

On u2204 (local), first plot is always void (black on black)
After that basic plots (`plot, findgen(10)` then `surface, dist(10)') are OK

On Debian 10 remotely + wx : first plot is OK *but* when plotting `plot, findgen(10)` the numbers at the buttom (below x-axis) are not visible and when  plotting `surface, dist(10)' one corner is not visible

On Mac, remote without wx : first plot OK but axes for Surface broken
Same problems for axes in Surface for u2204 & deb10 when compile with -DWXWDIGETS=off 
but are OK when compiled with the script but started with --no-use-wx !

PNG/JPEG OK as far I can test.

**Comment by GillesDuvert** [comment]
please test with todays version (after PR #1422)

**Comment by alaingdl** [comment]
(debian) using the script, remotely : first plot not appearing, then plot & surface & contour & axis OK
but, as show in "test_surface_basic", title is not at the expect place

(debian) cmake -DX11=on -DWXWIDGETS=off : first plot OK, contour OK. Surface is broken.

u2204 local + script :  first plot not appearing, then plot & surface & contour & axis OK
u2204 local + cmake  -DX11=on -DWXWIDGETS=off  :  first plot does appear, then plot & surface & contour & axis OK

what should I check ?

I am lost concerning the "local" driver versus the system one ...

**Comment by GillesDuvert** [comment]
> (debian) using the script, remotely : first plot not appearing, then plot & surface & contour & axis OK
> but, as show in "test_surface_basic", title is not at the expect place

script -> uses wxwidgets driver -> the first plot should appear now, as I explicitely demand the wxwidgets loop to update the screen at each graphic action! This is now the only, but very frustrating, 'last' bug. We cannot have the wxwidgets eventloop run outside the GDL loop (say, in a separate thread), it is not compatible with GDL structure.
The obvious solution would be to continue to favor X11 on unix, but this leads to future uncompatibility problems. Solving this eventloop problem needs a wxwidgets specialist as per the wxWidgets documentation everything is OK in the best of all worlds.

> (debian) cmake -DX11=on -DWXWIDGETS=off : first plot OK, contour OK. Surface is broken.

As soon as WXWIDGETS=OFF you are not testing much, as the X11 driver is not a problem (the driver "owns" the X11 plot window).
However, "broken surface" (see below) indicates you do not use our own xwin.so driver.

> u2204 local + script : first plot not appearing, then plot & surface & contour & axis OK

same as debian. I do not have this problem, but I use KDE not GNOME. This is really a wxwidgets against window manager issue.

> u2204 local + cmake -DX11=on -DWXWIDGETS=off : first plot does appear, then plot & surface & contour & axis OK

As I said, as soon as WXWIDGETS=OFF you are not testing much. Here you use our driver, that's all.

> what should I check ?
> 
> I am lost concerning the "local" driver versus the system one ...

Indeed it becomes difficult to understand what plplot drivers are used. The best solution for us would be to completely import the plplot essentials in GDL so as to not link at all against the installed plplot distribution.

We NEED to run our own version of the plplot drivers to get ALL the 3D functions working --- there is no other alternative. These modified drivers must be in the directory that GDL indicates at start:
`- Using local drivers in /usr/local/share/gnudatalanguage/drivers`
The drivers are copied there by the install command. So to be sure of our tests, only an installed GDL must be used. (since our drivers code are not often updated now, most of the time this is not really needed).
If GDL was using the plplot driver, not ours, then instead of
`!P.MULTI=[0,2,1] & window, xsize=400,ysize=200 & !P.T3D=1 & surfr & plot,dist(10) & surface,dist(10)`
producing
![image](https://user-images.githubusercontent.com/33936193/206174714-048236d2-aefd-46d4-b6e3-52927b076ca9.png)
one would get:
![image](https://user-images.githubusercontent.com/33936193/206174872-5f0b1743-dae1-41d5-9172-03c32cfe428e.png)
Which is normal since the 3D effects are in our driver now.
This test must be done preferably with the X11 or ps driver. With the wxwidgets driver, another difficulty is that the plplot wxwidgets driver may well be using a different version of the wxwidgets library than the one we use when building gdl, so if gdl does not use its own driver, the crash is unescapable.
