### ISSUE TITLE
PostScript coordinate issues.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1421]
There seems to still be a number of problems with PostScript output. Of particular concern is that different viewers seem to be interpreting the bounding box differently -- I've used `gv` both with BBOX view and A4 view, and also `okular` for a number of options of orientation and of page offsets. 

Default: `okular` shows a blank page, `gv` displays as expected in both views. 

Portrait: The same. (Expected but as well to check).
Portrait (full page): With offsets as determined to align page correctly in IDL. `okular` shows the plot cut off at top and right. `gv` shows the plot more-or-less as expected, but the labels look stretched. 

Landscape: `okular` recognizes landscape but shows plot cut off top and right again. `gv` shows plot small and truncates it in A4 view, landscape flag is not found. 
Landscape (with explicit page settings):  `okular` recognizes landscape but show plot cur off top and left. `gv` displays as expected but without recognizing a landscape orientation.

**ALL** cases show excessively long tick marks.

The attached file contains: the program to produce the test plots and also the outputs from IDL and GDL (git version 6662b5ab 5/12/22)

[gdl_ps_demo.tar.gz](https://github.com/gnudatalanguage/gdl/files/10153576/gdl_ps_demo.tar.gz)

I've not had a chance to check on a printer as I don't think my printer honours page offsets properly.

**Comment by GillesDuvert** [comment]
Hi James
Thanks for this complete report and examples.
I confirm 3 problems.
1.  the size of the tickmarks. Seen also on "z" device. Related to the wrong value of plplot units vs. physical size in all those drivers and the way GDL deals with this. Will see to it.
 1. the stretching of fonts in portrait mode. Related to the same difficulty above.
 1. how okular interprets ps files: the development and tests of the PS output was solely made with gv and bounding boxes seem OK in all cases. For GDL to reproducr the (very simple) IDL output is impossible due to plplot. 

Apparently some keyword or formatting in the header prevent okular to read correctly the gdl postscript files. I note that if a pdf is produced by `ps2pdf toto.ps`, then `toto.pdf` is correctly displayed by okular. Also, the gdl postcript files are correctly displayed by GIMP and (more surprisingly) OpenOffice. Not mentioning inclusion in TeX.

I will look to the 2 first issues but will need some advice on the third. What exactly makes okular fail?

**Comment by GillesDuvert** [comment]
1 and 2 above are solved in last PR.
Apparently Okular expects some hint on the orientation of the page, because landscape ps are more or less OK with it.
