### ISSUE TITLE
make check is in error and  question about the number of tests on Travis

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#143]
make check on my machine but it is the same on travis.
strangely travis passes 183 tests instead of the normal 202. 
Note that not all tests are supposed to pass anyway.
```
Makefile:117: recipe for target 'test' failed
gmake[4]: *** [test] Error 8
testsuite/CMakeFiles/check.dir/build.make:51: recipe for target 'testsuite/CMakeFiles/check' failed
make[3]: *** [testsuite/CMakeFiles/check] Error 2
CMakeFiles/Makefile2:216: recipe for target 'testsuite/CMakeFiles/check.dir/all' failed
make[2]: *** [testsuite/CMakeFiles/check.dir/all] Error 2
CMakeFiles/Makefile2:224: recipe for target 'testsuite/CMakeFiles/check.dir/rule' failed
make[1]: *** [testsuite/CMakeFiles/check.dir/rule] Error 2
Makefile:200: recipe for target 'check' failed
make: *** [check] Error 2

```

**Comment by slayoo** [comment]
That is intentional - for travis I've disabled tests that failed at "day zero" so that regressions would trigger failure messages.

The list of skipped tests is in the .travis.yml file:
https://github.com/gnudatalanguage/gdl/blob/master/.travis.yml#L18

The same list is verbosely included in ticket https://github.com/gnudatalanguage/gdl/issues/13 - thus closing this one.
