### ISSUE TITLE
test_dynamic_drivers fails with GDL 1.0.2 on Fedora Rawhide

### ISSUE THREAD

**Issue by opoplawski** [gnudatalanguage/gdl#1478]
Looking at updating GDL to 1.0.2 on Fedora rawhide I'm getting the following test failure:

```
test 80
        Start  80: test_dynamic_drivers.pro

80: Test command: /builddir/build/BUILD/gdl-1.0.2/build/src/gdl "-quiet" "-e" "if execute('test_dynamic_drivers') ne 1 then exit, status=1"
80: Working Directory: /builddir/build/BUILD/gdl-1.0.2/build/testsuite
80: Environment variables: 
80:  LC_COLLATE=C
80:  GDL_PATH=/builddir/build/BUILD/gdl-1.0.2/testsuite/:/builddir/build/BUILD/gdl-1.0.2/src/pro/
80:  GDL_STARTUP=
80:  IDL_STARTUP=
80: Test timeout computed to be: 3600
80: 
80: *** PLPLOT ERROR, ABORTING OPERATION ***
80: plInitDispatchTable: Could not open drivers directory, aborting operation
80: % Compiled module: TEST_DYNAMIC_DRIVERS.
80: % Compiled module: SURFR.
80: % Compiled module: SCALE3D.
 80/198 Test  #80: test_dynamic_drivers.pro ...........***Failed    0.27 sec
```

Is there some directory that needs to get specified?

**Comment by opoplawski** [comment]
We have a serious issue with where the drivers are installed.  Currently they are going to /usr/share/gnudatalanguage/drivers, but /usr/share is not an acceptable location for compiled binaries on Fedora.  They would need to go into /usr/lib{,64}/.  And it looks like a fair amount of work to split this out.

It seems like I may be able to specify PLPLOT_DRV_DIR to point to the temporary install location for running the tests.  We will see.

**Comment by GillesDuvert** [comment]
Hi @opoplawski 
this confirm my comment on #1479 

Do you refer to the location of gdl in general (that you can install everywhere) or the drivers in particular?
 
In this version, the location of the drivers is:` <where the gdl executable stays>/../share/gnudatalanguage/drivers`

So gdl can be another place than `/usr/local/bin/gdl` BUT the drivers (at least at the moment) need to be at .`./share/gnudatalanguage/drivers` relatively to the position of the gdl executable.

I must emphasize that we **use our own drivers now**. So the location of plplot's drivers is not important. What is important is that the plplot distro is compiled with  `-DENABLE_DYNDRIVERS=ON`. If it is not the case, and cannot be, then we are in trouble since gdl absolutely needs this plplot feature. The `/usr/share/gnudatalanguage` being the default location searched when plplot is not compiled with `-DENABLE_DYNDRIVERS=ON` seems to me another indication that indeed, the dynamic drivers are not set in fedora's plplot.
