### ISSUE TITLE
test_qhull fails with GDL 1.0.2 on Fedora Rawhide

### ISSUE THREAD

**Issue by opoplawski** [gnudatalanguage/gdl#1479]
Looking at updating GDL to 1.0.2 in Fedora, getting the following test failure:
```
        Start 150: test_qhull.pro

150: Test command: /builddir/build/BUILD/gdl-1.0.2/build/src/gdl "-quiet" "-e" "if execute('test_qhull') ne 1 then exit, status=1"
150: Working Directory: /builddir/build/BUILD/gdl-1.0.2/build/testsuite
150: Environment variables: 
150:  LC_COLLATE=C
150:  GDL_PATH=/builddir/build/BUILD/gdl-1.0.2/testsuite/:/builddir/build/BUILD/gdl-1.0.2/src/pro/
150:  GDL_STARTUP=
150:  IDL_STARTUP=
150: Test timeout computed to be: 3600
150: 
150: *** PLPLOT ERROR, ABORTING OPERATION ***
150: plInitDispatchTable: Could not open drivers directory, aborting operation
150: % Compiled module: TEST_QHULL.
150: % Compiled module: ERRORS_CUMUL.
150: % QHULL: Infinite or invalid (NaN) operands not allowed.
150: % QHULL: Infinite or invalid (NaN) operands not allowed.
150: % QHULL: qhull input error: separated input arrays must have same length and be 1 dimensional
150: /usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = lib::Vec3; _Alloc = std::allocator<lib::Vec3>; reference = lib::Vec3&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
150/198 Test #150: test_qhull.pro .....................Subprocess aborted***Exception:   0.66 sec
```
This is with qhull 7.2.1, which is fairly old at this point.  Is that an issue?

**Comment by opoplawski** [comment]
```
#6  lib::qgrid3_fun (e=0x5576e15a9600) at /home/orion/fedora/gdl/gdl-1.0.2/src/qhull.cpp:826
826           points[i] = { (*p0)[3*i], (*p0)[3*i+1], (*p0)[3*i+2] };
(gdb) print points
$1 = std::vector of length 0, capacity 0
(gdb) list
821         vector<Vec3> points;
822         points.reserve(np);
823
824         for (int i =0; i < np; i++)
825         {
826           points[i] = { (*p0)[3*i], (*p0)[3*i+1], (*p0)[3*i+2] };
827           //TODO handle not finite values
828         }
829
830         // vector holding all necessary info on the triangulation
(gdb) print np
$2 = 108
(gdb) print i
$3 = 0
```
I don't understand why points.reserve(np) does not seem to have increased the capacity of points.

**Comment by opoplawski** [comment]
So I guess this is conflation of resize() and reserve().  With reserve() I think you need to use push_back() here.  But I am not well versed in STL C++.

**Comment by GillesDuvert** [comment]
hello @opoplawski  thanks for the return.
Unfortunately the main worry that I have reading your report is that tiny little line of warning:
`150: plInitDispatchTable: Could not open drivers directory, aborting operation`
I'm afraid it proves the build is broken. There is a chance that all the graphic functions of GDL are broken because the plplot library is compiled without the   -DENABLE_DYNDRIVERS=ON  .
Normally there is a test (test_dynamic_drivers) that should fail in this case, indicating a build requirement is not served.
Alternatively, once gdl is built **and installed** (the latter is very important), then typing
```
$ gdl
(gdl starts...)
 plot,dist(10)
```
should open a window and plot something. All other cases (no plot, crash, other error) means the build is not good and/or we have to patch gdl.
