### ISSUE TITLE
SURFACE (and SHADE_SURF) do not play nicely with !p.multi

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1521]
Sorry, yet another 3-D plotting problem.
````
h = hanning(32,32)
window,xs=800,ys=400
!p.multi=[0,2,1]
surface,h
surface,h
window,xs=800,ys=800
!p.multi=[0,2,2]
surface,h
surface,h
surface,h
surface,h
````
From this is is clear that the plotting code is dividing up the X-Y plane into 2 or 4 sub windows rather than dividing the plotting area.
The two plot case
![2 plot case](https://user-images.githubusercontent.com/658624/220675302-cb855a60-8b9e-421c-8903-cbbdaba680bf.png)
The four plot case
![4 plot case](https://user-images.githubusercontent.com/658624/220675326-44b6165c-244b-4ff9-b823-7b418a562af7.png)
The results with `shade_surf` are the same.

**Comment by jtappin** [comment]
I've done a little more digging around, and find that `!p.region` and `!p.position` behave in the same way as `!p.multi` for surface type plots. 
Yet another awkwardness in relating IDL & PLPLOT coordinate systems (in the Fortran version of GRAFFER, I tend to find that breathing on code in that area is enough to break it)!

**Comment by GillesDuvert** [comment]
Actually IDL is more subtle (!) than that.
```
IDL> !P.MULTI=[0,2,2]
IDL>for i=0,3 do surface, hanning(32,32)
```
gives
![image](https://user-images.githubusercontent.com/33936193/220896098-3965b879-148f-4ecb-95f6-d0f66e99113b.png)
but
```
IDL> surfr
IDL> for i=0,3 do surface, hanning(32,32),/t3
```
gives
![image](https://user-images.githubusercontent.com/33936193/220896283-a0d703ba-18e1-42b9-b401-ade2b5970b5c.png)
which is what GDL does in all cases (because it uses only one transformation matrix in the modified drivers.)
Obviously this was too clever on my part. :smile:
