### ISSUE TITLE
Regression? Untested and false behaviour of GDL

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1537]
Wonder how this has passed unnoticed for so long --- probably a regression.

```
function zut
  a=reform(fltarr(2),2,1)
  return,a
end
```
```
IDL> b=zut()
% Compiled module: ZUT.
IDL> help,b
B               FLOAT     = Array[2, 1]
```

```
GDL> b=zut()
% Compiled module: ZUT.
GDL> help,b
B               FLOAT     = Array[2]
```
This is one of the main reasons why sswidl (the huge NASA ssw software) was giving strange errors with GDL. Theis software specifically likes false 2-dim data with last dim==1

**Comment by jtappin** [comment]
It's actually IDL that's being inconsistent.
````
IDL> a = fltarr(2,1)
IDL>  help, a
A               FLOAT     = Array[2]
IDL> 
````

**Comment by GillesDuvert** [comment]
indeed :smile: 
But we have to preserve IDL's foibles ... Especially if legacy code depend on them

**Comment by jtappin** [comment]
That's true. I didn't even know that IDL could be tricked into making an array with a final dimension of length 1, but for **most** purposes it makes little difference as:
````
a = fltarr(n)
b = a[*,*]
c=a[*,intarr(n)]
````
works fine. The problem is when someone uses `size` and looks for the second dimension (I know there are work-arounds galore for that in `graffer`).

**Comment by GillesDuvert** [comment]
Apparently there for ages. And indeed the main culprit of sswidl not working yet, for exactly the reason cited above: using size() ..
One-lined patch soon.
