### ISSUE TITLE
Documentation wrong for mpfit

### ISSUE THREAD

**Issue by jaymurthy** [gnudatalanguage/gdl#1688]
The documentation says that a function is needed but it is really a procedure that is needed. The call is to CALL_PROCEDURE and not to CALL_FUNCTION. It requires a fair bit of updation of the mpfit documentation. I can do that if you would like. This affects a number of routines like Gaussfit or Curvefit.

Jayant

**Comment by alaingdl** [comment]
If I remember well, MPFIT has a procedure and a function interfaces ...

1. Which version of GDL are you using ? Because the code for GAUSSFIT() was totally rewritten recently, available in the Git version.
2. Documentation for MPfit is here https://pages.physics.wisc.edu/~craigm/idl/cmpfit.html
3. do you use : git clone https://salsa.debian.org/debian-astro-team/mpfit (as mentioned in 
https://github.com/gnudatalanguage/gdl/wiki/Third-party-librairies )
5. example in testsuite/interactive_tests/test_mpfit.pro

HTH

Alain

**Comment by jaymurthy** [comment]
I'm using gdl 1.0.3 and the latest version of mpfit (1.85) and mpcurvefit (1.12). Actually, I misstated the problem, now that I look at it more carefully. The example correctly shows that a procedure must be used (because CALL_PROCEDURE is used). I was confused because the description talks about a function which returns the model value. I guess the example makes it clear though. 

I would change the word function to procedure, though.

USER FUNCTION
;
;  The user must define a function which returns the model value.  For
;  applications which use finite-difference derivatives -- the default
;  -- the user function should be declared in the following way:
;
;    ; MYFUNCT - example user function
;    ;   X - input independent variable (vector same size as data)
;    ;   P - input parameter values (N-element array)
;    ;   YMOD - upon return, user function values
;    ;   DP - upon return, the user function must return
;    ;          an ARRAY(M,N) of derivatives in this parameter
;    ;
;    PRO MYFUNCT, x, p, ymod, dp

**Comment by GillesDuvert** [comment]
@alaingdl I'm confused: Since the rewriting of gaussfit in pure gdl/C++ I thought the GDL package was not dependent on Craig Markwart's MPFIT and associated procedures. So the subdirectory pro/CMprocedures containing them should be deleted? (meaning people would use, if they need to, the MPFIT that can be found in, I presume, the IDLAstro library, independently from GDL)

**Comment by alaingdl** [comment]
@GillesDuvert I don't think so, since POLY_FIT()) is still using MPFIT. Furthermore I keep the MPFIT inside GAUSSFIT() just in case (some cases are tricky when poly part is stronger than gaussian shape : having an alternative is not stupid so far)

**Comment by alaingdl** [comment]
I think we can close this issue, the discussion clarifies several points
