### ISSUE TITLE
symlinked directories should be expanded by EXPAND_PATH

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#217]
As reported by @GillesDuvert on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/624/):

EXPAND_PATH does not see (linux) directories that are symlinks. This because glob() does not see them either...
IDL does.
Not very important but should be known and hopefully cured.

**Comment by slayoo** [comment]
@maynardGK as per your comments to the SF issue and your work on file-related routines, i believe this might have been addressed to some extent - could you please comment. Thanks!

**Comment by maynardGK** [comment]
This is solved already since 9.6 or earlier. I checked just now on linux where I have a symlink to 
D:/home/greg in my ~/ directory.
GDL> ff = expand_path("+~/",count=nd) & ffsp=strsplit(ff,":",count=nds,/extract) & print,nd,nds             
          37          37
GDL> for k=0,36 do print,ffsp[k]
/home/greg/gdlpro
/home/greg/d/dev
/home/greg/d/gdlpro/aacmlib/arrays
/home/greg/d/gdlpro/aacmlib/cmsvlib/new
/home/greg/d/gdlpro/aacmlib/cmsvlib
 ... etc...
/home/greg/d/testsuite
/home/greg/d/graveyard
/home/greg/d
/home/greg/chromed/gdlidl
/home/greg/chromed/gdl-0.9.8/src/pro/dicom
/home/greg/chromed/gdl-0.9.8/src/pro/obsolete

where ~/d is a symlink to D:/home/greg and ~/chromed:
rwxrwxrwx  1 greg users      20 Mar 23  2015 chromed -> '/d/Chrome Downloads/'
 
For WIN32 it seems to be working, also. In GDL we have an extra keyword, PATTERN, than can be used with expand_path. In Windows7 I have a number of symlinks out of C:/usr
GDL>tf=expand_path("+C:/usr",patt="*.dll.a",count=nd)
GDL> print,nd
           2
GDL> print,tf
 C:/usr/lib64;C:/usr/local32d/lib
 GDL> ef=expand_path("+C:/usr",patt="*.exe",count=nd) & print,nd
           5
GDL> print,ef
C:/usr/bin;C:/usr/bin32/mingw;C:/usr/bin32/mingworg;C:/usr/bin64/mingw;C:/usr/local32d/bin

The local32d symlink points to another disk and there were .exe files found in ./bin

GDL> $ls -lat C:/usr
total 110
drwxr-xr-x 1 greg None     0 Apr 16 04:52 ..
drwxr-xr-x 1 greg None     0 Jan 26 23:11 bin32
drwxr-xr-x 1 greg None     0 Jan 15 01:24 bin64
drwxr-xr-x 1 greg None     0 Jan 12 13:25 share
drwxr-xr-x 1 greg None     0 Jan 24  2016 bin
drwxr-xr-x 1 greg None     0 Sep 23  2015 sh
drwxr-xr-x 1 greg None     0 Sep 23  2015 .
lrwxrwxrwx 1 greg None    18 Sep  8  2015 local32d -> /msysD/usr/local32
-rw-r--r-- 1 greg None     6 May 29  2015 s2.txt
lrwxrwxrwx 1 greg None    21 Apr 19  2015 lib64 -> /c/mingw/dll64-psxseh
lrwxrwxrwx 1 greg None    21 Apr 19  2015 lib32 -> /c/mingw/dll32-psxdw2

**Comment by GillesDuvert** [comment]
indeed, expand_path is now correct wrt. this problem. closed.
