### ISSUE TITLE
dreary state of the testsuite on Windows (at least the appveyor set-up)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#327]
Here is the list of tests which are disabled as of now on appveyor as they were failing from the get-go (good news is that another >100 tests pass!), @pjb7687 @maynardGK - please help!:
- [ ] test_bug_3300626.pro
- [ ] test_bug_3275334.pro
- [ ] test_bug_3104214.pro
- [ ] test_bug_2876161.pro
- [ ] test_bug_2610174.pro
- [ ] test_bug_1779553.pro
- [ ] test_bug_3394430.pro
- [ ] test_bug_3595172.pro
- [ ] test_bug_635.pro
- [ ] test_bug_709.pro
- [ ] test_bug_719.pro
- [ ] test_bug_n000587.pro
- [ ] test_bug_n000608.pro
- [ ] test_bug_n000720.pro
- [ ] test_byte_conversion.pro
- [ ] test_call_external.pro
- [ ] test_chisqr_cvf.pro
- [ ] test_clip.pro
- [ ] test_congrid.pro
- [ ] test_constants.pro
- [ ] test_correlate.pro
- [ ] test_device.pro
- [ ] test_dicom.pro
- [ ] test_execute.pro
- [ ] test_extra_keywords.pro
- [ ] test_fft_dim.pro
- [ ] test_file_basename.pro
- [ ] test_file_copy.pro
- [ ] test_file_delete.pro
- [ ] test_fft_leak.pro
- [ ] test_file_dirname.pro
- [ ] test_file_lines.pro
- [ ] test_file_move.pro
- [ ] test_file_search.pro
- [ ] test_file_test.pro
- [ ] test_file_which.pro
- [ ] test_fix.pro
- [ ] test_finite.pro
- [ ] test_fixprint.pro
- [ ] test_formats.pro
- [ ] test_fx_root.pro
- [ ] test_fz_roots.pro
- [ ] test_gc.pro
- [ ] test_get_lun.pro
- [ ] test_get_screen_size.pro
- [ ] test_gh00178.pro
- [ ] test_hist_2d.pro
- [ ] test_idlneturl.pro
- [ ] test_indgen.pro
- [ ] test_interpol.pro
- [ ] test_l64.pro
- [ ] test_la_least_squares.pro
- [ ] test_ludc_lusol.pro
- [ ] test_make_dll.pro
- [ ] test_math_function_dim.pro
- [ ] test_matrix_multiply.pro
- [ ] test_memory.pro
- [ ] test_message.pro
- [ ] test_moment.pro
- [ ] test_multiroots.pro
- [ ] test_obj_isa.pro
- [ ] test_obj_new.pro
- [ ] test_plot_oo.pro
- [ ] test_plot_ranges.pro
- [ ] test_plotting_ranges.pro
- [ ] test_pmulti.pro
- [ ] test_point_lun.pro
- [ ] test_postscript.pro
- [ ] test_product.pro
- [ ] test_ps_decomposed.pro
- [ ] test_python.pro
- [ ] test_image_statistics.pro
- [ ] test_n_tags.pro
- [ ] test_nans_in_sort_and_median.pro
- [ ] test_nestedloop.pro
- [ ] test_parse_url.pro
- [ ] test_python_module_0.pro
- [ ] test_python_module_1.pro
- [ ] test_python_module_2.pro
- [ ] test_qhull.pro
- [ ] test_random.pro
- [ ] test_readf.pro
- [ ] test_resolve_routine.pro
- [ ] test_same_name.pro
- [ ] test_simplex.pro
- [ ] test_spawn_unit.pro
- [ ] test_spher_harm.pro
- [ ] test_spl_init.pro
- [ ] test_step.pro
- [ ] test_str_sep.pro
- [ ] test_stregex.pro
- [ ] test_strmatch.pro
- [ ] test_strsplit.pro
- [ ] test_structures.pro
- [ ] test_systime.pro
- [ ] test_tic_toc.pro
- [ ] test_total.pro
- [ ] test_rounding.pro
- [ ] test_tv.pro
- [ ] test_typename.pro
- [ ] test_wait.pro
- [ ] test_wavelet.pro
- [ ] test_window_background.pro
- [ ] test_wordexp.pro
- [ ] test_zeropoly.pro
- [ ] test_zip.pro
- [ ] test_delvarrnew.pro
- [ ] test_hash.pro
- [ ] test_list.pro
- [ ] test_obj_valid.pro
- [ ] test_make_array.pro
- [ ] test_ptr_valid.pro

**Comment by maynardGK** [comment]
The Appveyor build is not a functional GDL until the support libraries are copied into the artifact
that it produces. If we can get it into an MSYS scripting mode (with supporting tar execution) we could download from the MSYS repository and skip the building of support libraries except for BSD-XDR and for plplot.  Some patching is still required on-the-fly; I have some C++ patches for plplot drivers and the bin/wx-config may also need patching so that the build will function.

As for launchtest.c, the one issue I saw at the outset was the diversion of stdout to /dev/null which
doesn't work well in MSYS, which wants to literally find a /dev/null or something.  The tests themselves, in general, pass when run from a GDL session.

**Comment by slayoo** [comment]
@maynardGK I do understand that there are multiple ways of building GDL on Windows and it would be great to have these multiple ways supported on appveyor in separate builds - please help with a PR. 

Copying the libraries into the artefact archive would make it possible to run the built package on other computers, and this it not ready IIUC (and as you've pointed out in the relevant ticket, we would also need to copy the sources to make such artefact license compliant) - PR also welcome. 

There are, in general many things to improve in the appveyor script besides the above as well: 64-bit build, Debug/Release build, codecov build, Python module build, etc (trying to keep a list of these here: https://github.com/gnudatalanguage/gdl/issues/242)

Yet still, (and first of all) we have a valid way of building the software which results in roughly 50% of tests to pass and 50% of tests to fail - right?

**Comment by maynardGK** [comment]
Here I've started to go through the tests listed; those that won't work are commented out with 
how they fail.  Generally, trouble will happen when probing the display hardware, and spawning.
Also the edge-effects of formatting and weird numbers.

`;test_bug_3300626% TEST_BUG_3300626: Error opening file. Unit: 100, File: /dev/zero
;test_bug_3275334% TVRD: Unable to read from current device: WIN
;  test_bug_3104214 ; set_plot,'z'
; spawn,'../src/gdl -quiet -e ' ...
;  test_bug_2876161
  test_bug_2610174
;  test_bug_1779553 e and g formats
  test_bug_3394430
  test_bug_3595172
;  test_bug_635 % TEST_BUG_635: MISSING file : test_bug_635.dat
  test_bug_709  ; 7 errors
  test_bug_719  ; 0 errors
;  test_bug_n000587 ; !stime
  test_bug_n000608  ; help,output=a not operational in simple case (patched)
;  test_bug_n000720  ; passes with file_etc. file to be created : ~/test_GDL_openu_12345fake.txt
  test_byte_conversion ; passes
; no response  test_call_external
  test_chisqr_cvf
;  test_clip ; (gdlf) succeeds if first to be run: fails after test_chisqr_cvf
   test_congrid; % WINDOW: Routine is not defined for current graphics device.
; % Execution halted at: TEST_CONGRID_ON_IMAGES    71 F:\github\gdlgit\testsuite\test_congrid.pro
;  test_constants% IMSL_CONSTANT: GDL was compiled without support for UDUNITS
  test_correlate
;
;Calling TEST_DEVICE_X with X11 on
;  test_device% DEVICE: Keyword GET_VISUAL_NAME not allowed for call to: DEVICE

;  test_dicom crash APPCRASH
  test_execute ; pass
  test_extra_keywords
;% Compiled module: TEST_EXTRA_KEYWORDS.
;{ IDL_M_FAILURE IDL_MBLK_CORE          -1           0           0
;  EXECUTE: Expression must be scalar in this context: <Expression> <STRING    Array[1]>  % }
;{ IDL_M_FAILURE IDL_MBLK_CORE          -1           0           0
;  EXECUTE: Expression must be scalar in this context: <Expression> <STRING    Array[1]>  % }
;% Compiled module: DIST.
;       1       1      86.4105      4260.85
;       1       1      86.4105      86.4105

  test_fft_dim
;  test_file_basename% TEST_FILE_BASENAME: FILE_BASENAME(GDLTokenTy\*) NE GDLTokenTy\*
;  test_file_copy; Almost, with spawn:
;COPY N1
;COPY N2
; FILE_COPY: gdlfd_test1a overwrite not allowed
; FILE_COPY: gdlfd_test1b overwrite not allowed
;OVERWRITE
;Require_dir
; FILE_COPY: require_directory, gdlfd_test1aCP is not a valid directory
; FILE_COPY: require_directory, gdlfd_test1bCP is not a valid directory
;% FILE_COPY:  destination array must be same size as source
;% Execution halted at: TEST_FILE_COPY     156 F:\github\gdlgit\testsuite\test_file_copy.pro
;%                      $MAIN$
  test_file_delete ; pass
  test_fft_leak ; % TEST_FFT_LEAK: NO case of memory leak when calling FFT have been found
;  test_file_dirname ; % TEST_FILE_DIRNAME:  FILE_DIRNAME(GDLTokenTy\*) NE .
  test_file_lines ; % FILE_LINES: Could not open file for reading ; get in testsuite directory
;
  test_file_move ; % Expression must be a scalar or 1 element array in this context.
;% Execution halted at: FILE_MOVE           50 F:\github\gdlgit\src\pro\file_move.pro
;---  test_file_search
;  test_file_test
  test_file_which
;  test_fix % TEST_FIX_NAN_INF: Error on operation : pb with type : INT
;exp :       0       0      10     -10       0       0       0       0
;res :       0       0      10     -10  -32768  -32768  -32768  -32768
;% TEST_FIX_NAN_INF:   1 errors encountered during TEST_FIX_NAN_INF tests
  test_finite
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        8
% TEST_FINITE_BASIC:   2 errors encountered during TEST_FINITE_BASIC tests
% TEST_FINITE_BASIC: Error on operation : problem with Case        5
% TEST_FINITE_BASIC: Error on operation : problem with Case        8
% TEST_FINITE_BASIC:   2 errors encountered during TEST_FINITE_BASIC tests
% TEST_FINITE_VALUES:   NO errors encountered during TEST_FINITE_VALUES tests

`
When the new file_etc branch comes in (with modified tests) there should be a lot better test_file_
results.

**Comment by maynardGK** [comment]
Here are the remainder of my results of running the tests from a GDL session tests without a ";"
in column 1 passed. Otherwise the reason/message is indicated.
  test_fixprint
;  test_formats;% Expression must be a scalar or 1 element array in this context.
;% Execution halted at: FILE_COPY           36 F:\github\gdlgit\src\pro\file_copy.pro
;%                      GENERATE_FORMATS_FILE    72 F:\github\gdlgit\testsuite\test_formats.pro
;%                      TEST_FORMATS       148 F:\github\gdlgit\testsuite\test_formats.pro
;%                      $MAIN$
  test_fx_root
  test_fz_roots
;--  test_gc; this test does not pass on idl, SO IT IS FALSE.
  test_get_lun
;  test_get_screen_size;% GET_SCREEN_SIZE: Too many arguments.
  test_gh00178
  test_hist_2d
;  test_idlneturl;% FILE_DELETE: Sorry, FILE_DELETE is not available on Windows (FixMe!)
;  test_indgen ; parallel large bindgen/findgen/indgen/cindgen yields wrong results
  test_interpol
;  test_l64 ;Segmentation fault (program is not 64-bit)
  test_la_least_squares
  test_ludc_lusol
;  test_make_dll;% CALL_EXTERNAL: Error opening shared object: F:/github/gdlgit\GDL_test_make_dll.so
;Working here : F:/github/gdlgit\
;% Compiled module: MAKE_DLL.
;% Compiled module: PATH_SEP_ADD.
;F:\github\gdlgit\testsuite\test_make_dll.c
;/tmp/\test_make_dll.o
;F:/github/gdlgit\GDL_test_make_dll.so
;====
  test_math_function_dim
  test_matrix_multiply
;  test_memory% TEST_MEMORY: reported memory consumption should increase after allocating a big array!
  test_message
  test_moment
  test_multiroots
  test_obj_isa
;  test_obj_new ; gdlffdicom__dictionary has too many lines.
;  % Compiled module: TEST_OBJ_NEW.
;% Compiled module: GDLFFDICOM__DEFINE.
;% Compiled module: GDLFFDICOM__ASSOC__DEFINE.
;
;greg@Homerw7  /f/github/gdlgit
;  test_plot_oo% DEVICE: Current device does not support keyword FILENAME.
  test_plot_ranges
  test_plotting_ranges
;  test_pmulti TEST_PMULTI: Error opening file.device, filename='/dev/null'
;  test_point_lun ; file_copy fluke - OK with new file_etc.
;  test_postscript% SET_PLOT: Device not supported/unknown: X
;% Execution halted at: TEST_POSTSCRIPT_BASIC   104 F:\github\gdlgit\testsuite\test_postscript.pro
;%                      TEST_POSTSCRIPT    110 F:\github\gdlgit\testsuite\test_postscript.pro
  testduct.pro
  test_ps_decomposed
;  test_python ; (not compiled with python)
  test_image_statistics
;  test_n_tags ; 20 errors
  test_nans_in_sort_and_median
  test_nestedloop
  test_parse_url
;  test_python_module_0% TEST_PYTHON_MODULE_0: ../src/.libs/libgdl.so not found
;  test_python_module_1
;  test_python_module_2
  test_qhull  ; % TEST_GAUSS2D_ON_SPIRAL: Ambiguous: Variable is undefined: GAUSS2DFIT or: Function not found: GAUSS2DFIT
;  test_random ; % DEVICE: Keyword GET_DECOMPOSED not allowed for call to: DEVICE
  test_readf
  test_resolve_routine
;Problem in : test_get_screen_size
;Problem in : test_indgen
;Due to problem, will skip next test.
;% Compiled module: BANNER_FOR_TESTSUITE.
;% Compiled module: GDL_IDL_FL.
;% TEST_ALL_TEST_ROUTINES:   2 errors encountered during TEST_ALL_TEST_ROUTINES tests
;% Compiled module: ERRORS_CUMUL.
;% TEST_RESOLVE_ROUTINE: ============================================================
;% TEST_RESOLVE_ROUTINE: =                                                          =
;% TEST_RESOLVE_ROUTINE: =  2 errors encountered during TEST_RESOLVE_ROUTINE tests  =
;% TEST_RESOLVE_ROUTINE: =                                                          =
;% TEST_RESOLVE_ROUTINE: ============================================================
  test_same_name
  test_simplex
;  test_spawn_unit;% SPAWN: UNIT keyword is not implemented yet!
  test_spher_harm
  test_spl_init
;  test_step;% Type conversion error: Unable to convert given STRING: '".compile test_step.pro ' to INT.
  test_str_sep
  test_stregex
  test_strmatch
  test_strsplit
  test_structures
  test_systime
;% Compiled module: TEST_SYSTIME.
;% TEST_SYSTIME_LOCALE: Problem with LOCALE in GDL
;% TEST_SYSTIME_LOCALE:   1 errors encountered during TEST_SYSTIME_LOCALE tests
;% Compiled module: ERRORS_CUMUL.
;% TEST_SYSTIME_ZERO:   NO errors encountered during TEST_SYSTIME_ZERO tests
;% Compiled module: ERRORS_ADD.
;% TEST_SYSTIME_EPOCH: Error on operation : Unix billennium conversion failed !
;% TEST_SYSTIME_EPOCH: Error on operation : Decimal Row Keyboard conversion failed !
;% TEST_SYSTIME_EPOCH:   2 errors encountered during TEST_SYSTIME_EPOCH tests
;% TEST_SYSTIME_JULIAN: Not finished
;% TEST_SYSTIME_JULIAN: Not finished, please contributed !
;% TEST_SYSTIME_JULIAN: Not finished
;% TEST_SYSTIME_JULIAN:   NO errors encountered during TEST_SYSTIME_JULIAN tests
;% TEST_SYSTIME: ====================================================
;% TEST_SYSTIME: =                                                  =
;% TEST_SYSTIME: =  3 errors encountered during TEST_SYSTIME tests  =
;% TEST_SYSTIME: =                                                  =
;% TEST_SYSTIME: ====================================================
  test_tic_toc
;  test_total;% TEST_TOTAL_LARGE: Array requires more memory than available
;% Execution halted at: TEST_TOTAL_LARGE   153 F:\github\gdlgit\testsuite\test_total.pro
  test_rounding
;% TEST_ROUNDING_L64: Error on operation : bad value type LONG, case Pos.
;% TEST_ROUNDING_L64: =                                                       =
;% TEST_ROUNDING_L64: =  1 errors encountered during TEST_ROUNDING_L64 tests  =
;% TEST_ROUNDING_L64: =                                                       =
;% TEST_ROUNDING_L64: testing /FLOOR
;% TEST_ROUNDING_L64: Error on operation : bad value type LONG, case Neg.
;% TEST_ROUNDING_L64: =                                                       =
;% TEST_ROUNDING_L64: =  1 errors encountered during TEST_ROUNDING_L64 tests  =
;% TEST_ROUNDING_L64: =                                                       =
;% TEST_ROUNDING_L64: ==========================================================
;% TEST_ROUNDING: =====================================================
;% TEST_ROUNDING: =                                                   =
;% TEST_ROUNDING: =  2 errors encountered during TEST_ROUNDING tests  =
;% TEST_ROUNDING: =                                                   =
;% TEST_ROUNDING: =====================================================  
;  test_tv% TVRD: Unable to read from current device: WIN.
;  test_typename; uses ffdicom (see test_obj_new)
  test_wait
  test_wavelet
;  test_window_background% TVRD: Unable to read from current device: WIN.
;  test_wordexp% TEST_WORDEXP: This code is not design for MSwin plateform
  test_zeropoly
;  test_zip;% TEST_ZIP: the option used by STAT is not working, please report
;  test_delvarrnew ; spawn environment in windows
  test_hash ; fixed  in test (reduced capabilities)
  test_list ; fixed in test
  test_obj_valid
  test_make_array
  test_ptr_valid

**Comment by maynardGK** [comment]
make check with mingw GDL  build:
\# First to filter the "dead-end" tests:
sed -e "s;add_test(test_bug_3055720;#add_test(_3055720;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_bug_3057520;#add_test(_3057520;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_bug_3061072;#add_test(_3061072;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_bug_3100945;#add_test(_3100945;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_bug_3275334;#add_test(_3275334;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_bug_3300626;#add_test(_3300626;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_dicom.pro;#add_test(_dicom.pro;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_file_lines.pro;#add_test(_file_lines.pro;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_postscript.pro;#add_test(_postscript.pro;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_ps_decomposed.pro;#add_test(_ps_decomposed.pro;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_total.pro;#add_test(_total.pro;" -i testsuite/CTestTestfile.cmake
sed -e "s;add_test(test_zip.pro;#add_test(_zip.pro;" -i testsuite/CTestTestfile.cmake
$ make check

68% tests passed, 65 tests failed out of 200

Total Test time (real) =  48.85 sec

The following tests FAILED:
          1 - test_angles.pro (SEGFAULT)
          5 - test_base64.pro (SEGFAULT)
          6 - test_binfmt.pro (SEGFAULT)
          7 - test_bug_1779553.pro (Failed)
         12 - test_bug_2876161.pro (Failed)
         54 - test_bug_719.pro (SEGFAULT)
         58 - test_bug_n000587.pro (Failed)
         65 - test_bytscl.pro (SEGFAULT)
         66 - test_call_external.pro (Failed)
         73 - test_common.pro (SEGFAULT)
         74 - test_congrid.pro (SEGFAULT)
         75 - test_constants.pro (SEGFAULT)
         77 - test_correlate.pro (SEGFAULT)
         78 - test_delvarrnew.pro (Failed)
         80 - test_device.pro (SEGFAULT)
         82 - test_erfinv.pro (SEGFAULT)
         87 - test_fft_leak.pro (SEGFAULT)
         88 - test_file_basename.pro (Failed)
         89 - test_file_copy.pro (SEGFAULT)
         92 - test_file_move.pro (SEGFAULT)
         94 - test_file_test.pro (SEGFAULT)
         95 - test_file_which.pro (Failed)
         96 - test_finite.pro (SEGFAULT)
         97 - test_fix.pro (Failed)
         98 - test_fixprint.pro (SEGFAULT)
        101 - test_fz_roots.pro (SEGFAULT)
        104 - test_get_screen_size.pro (SEGFAULT)
        105 - test_gh00178.pro (SEGFAULT)
        115 - test_image_statistics.pro (SEGFAULT)
        116 - test_indgen.pro (SEGFAULT)
        117 - test_interpol.pro (SEGFAULT)
        122 - test_l64.pro (SEGFAULT)
        123 - test_la_least_squares.pro (SEGFAULT)
        127 - test_make_dll.pro (SEGFAULT)
        128 - test_math_function_dim.pro (SEGFAULT)
        130 - test_memory.pro (SEGFAULT)
        131 - test_message.pro (SEGFAULT)
        132 - test_modulo.pro (SEGFAULT)
        133 - test_moment.pro (SEGFAULT)
        136 - test_n_tags.pro (SEGFAULT)
        142 - test_obj_isa.pro (SEGFAULT)
        144 - test_obj_valid.pro (SEGFAULT)
        145 - test_parse_url.pro (SEGFAULT)
        148 - test_plotting_ranges.pro (Failed)
        149 - test_pmulti.pro (SEGFAULT)
        153 - test_ptrarr.pro (SEGFAULT)
        154 - test_ptr_valid.pro (SEGFAULT)
        158 - test_python_module_2.pro (SEGFAULT)
        162 - test_random.pro (SEGFAULT)
        166 - test_resolve_routine.pro (SEGFAULT)
        168 - test_rounding.pro (SEGFAULT)
        172 - test_scope_varfetch.pro (SEGFAULT)
        177 - test_spl_init.pro (SEGFAULT)
        179 - test_step.pro (Failed)
        183 - test_strmatch.pro (SEGFAULT)
        184 - test_strsplit.pro (SEGFAULT)
        187 - test_systime.pro (SEGFAULT)
        189 - test_trisol.pro (SEGFAULT)
        190 - test_tv.pro (Exit code 0xcfffffff
)
        191 - test_typename.pro (SEGFAULT)
        193 - test_wait.pro (Failed)
        194 - test_wavelet.pro (SEGFAULT)
        196 - test_window_background.pro (SEGFAULT)
        199 - test_xdr.pro (SEGFAULT)
        200 - test_zeropoly.pro (SEGFAULT)
running a few from the interactive shell:
greg@Homerw7  /f/github/gdlgit
$ gdlgit

  GDL - GNU Data Language, Version 0.9.8 git

- For basic information type HELP,/INFO
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set).
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

GDL> test_obj_isa
% Compiled module: TEST_OBJ_ISA.
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_OBJ_ISA: =====================================================
% TEST_OBJ_ISA: =                                                   =
% TEST_OBJ_ISA: =  NO errors encountered during TEST_OBJ_ISA tests  =
% TEST_OBJ_ISA: =                                                   =
% TEST_OBJ_ISA: =====================================================
GDL> test_obj_valid
% Compiled module: TEST_OBJ_VALID.
SUCCESS
GDL> test_ptrarr
% Compiled module: TEST_PTRARR.
% Compiled module: DIST.
GDL> test_ptr_valid
% Compiled module: TEST_PTR_VALID.
%  TEST_PTR_VALID: ========================================================
%  TEST_PTR_VALID: =                                                      =
%  TEST_PTR_VALID: =  NO errors encountered during  TEST_PTR_VALID tests  =
%  TEST_PTR_VALID: =                                                      =
%  TEST_PTR_VALID: ========================================================
Success!
GDL> test_strmatch
% Compiled module: TEST_STRMATCH.
% Compiled module: STRMATCH.
GDL>

**Comment by slayoo** [comment]
let's close this one, and first do #615!
