### ISSUE TITLE
Windows build problems and discussion

### ISSUE THREAD

**Issue by sflinois** [gnudatalanguage/gdl#427]
Opening a topic about GDL build on Windows

The focus of this discussion is to solve problems to automate GDL build on MSYS.
And, on a longer term, to be able to build GDL on native Windows (With Visual Studio or Clang)

you can find more info on windows build here : 
https://github.com/gnudatalanguage/gdl/issues/242
https://github.com/gnudatalanguage/gdl/pull/416

**Comment by maynardGK** [comment]
I have been working with the Appveyor build effected via the  appveyor.yml file in the git distribution.
#408 
 scripts/mingw-bldgdl.bat and scripts/installgdl.ps1 are copied from the appveyor build.
  To replicate what appveyor does at home, make a C:\projects folder and make a symlink called gdl pointing to the git. This can be done to a separate disk (with lots of space).
Also, make a symlink at top-level C: to mingw-w64 so that C:\mingw-w64\ points to where the mingw-w64 distributions are kept (again, a different disk than C: which may have space constraints). With these file system changes you can cut-and-paste to replicate the build done by appveyor.  Another link is to match the name of the compiler distro in the appveyor build with the one you have at home.  So my d:/mingw-w64/ directory looks like so:

07/01/2018  09:47 PM    \<DIR\>          i686-5.4.0-posix-dwarf-rt_v5-rev0
07/01/2018  09:38 PM        42,692,388 i686-5.4.0-release-posix-dwarf-rt_v5-rev0.7z
07/21/2018  12:07 AM    \<SYMLINKD\>     i686-6.3.0-posix-dwarf-rt_v5-rev1 [i686-6.4.0-posix-dwarf-rt_v5-rev0]
07/02/2018  11:54 AM    \<DIR\>          i686-6.4.0-posix-dwarf-rt_v5-rev0
06/30/2018  05:55 PM        42,648,051 i686-6.4.0-release-posix-dwarf-rt_v5-rev0.7z
07/09/2018  01:30 PM    \<DIR\>          i686-7.3.0-posix-dwarf-rt_v5-rev0
07/07/2018  04:09 PM        44,677,667 i686-7.3.0-release-posix-dwarf-rt_v5-rev0.7z

You can make symlinks in windows from an MSYS shell run "as an administrator" and where you export the environment MSYS=winsymlinks:nativestrict 

Update:
https://ci.appveyor.com/project/slayoo/gdl/build/1.0.564

is the latest build, which includes graphicsMagick at 8-bit resolution, and connects to wingdi for the "WIN" plot device.  The artifact from this build (GDL_BUILD.zip) can be directly run (i.e.. clcked from explorer) provided the PLPLOT logicals are set up ok (note included about this in the artifact).

  The commit history of #408 is a saga of how to do anything else wrong to prevent a good appveyor build.  One step now is to attempt to compile, for quantum depth 32, the GraphicsMagick distribution.
Something about the MSYS setup in appveyor prevents the (./configure-based) build from completing.
The commands can be implemented from an operating MSYS (i.e., my home system) and GM-Q32 is
made without problems.

**Comment by maynardGK** [comment]
When I run this (https://ci.appveyor.com/api/buildjobs/tcgs0xqu17h7o7jn/artifacts/gdl_build.zip) on my windows' computer the behavior is as expected.   The file unpacks into at least build/ and install/ trees.  This particular build was number 593 now replaced by 600 (see comment below); it includes FFTW, eigen3, and 8-bit GraphicsMagick and uses the wingdi plot driver.  **PLEASE TEST THIS AND REPLY HERE IF YOU HAVE PROBLEMS** (also separately for the HASH and LIST functions).  In particular, the console behavior may not be good, depending on the windows' system you use and the method you use to invoke GDL: see below for hints if you have such problems.  The build/ directory can be discarded but the install/ directory is a drop-in: it should work for any system (Win7 or better) and includes instructions (INSTALL.plplot) on how to get things going, for novice users.

The commits of #408 are now part of #431.
Presumably, the PR #431 will be soon merged into master so a pull/merge need not happen in order to get the source scripts I am referencing.  Also, with this update, HASH() and LIST() are updated as far as I have gone, which is nearly full functionality.    All of the articfact is contained in sub-directories, so you may unpack it in your git directory of GDL without issue.  If you wish, a new build  can be made with support libraries generated in build 556, https://ci.appveyor.com/api/buildjobs/477r04r1mafk6qi5/artifacts/gdl_build.zip
When #431 has been merged the scripts called from appveyor.yml can be easily followed.  Symbolic links (described in note above) will align your git files with the directories referenced in those scripts.

I run windows 7 (home premium) 64-bit.  All of the support libraries are included in the distribution, so  begin testing by double-clicking on the "gdl.exe" file (found in gdl_build.zip as install/gdl/bin/gdl.exe).   

  GDL - GNU Data Language, Version 0.9.8 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

 \% Compiled module: PATH_SEP.
GDL> help,!path
<Expression>    STRING    = 'F:/github/gdlgit/src/pro/dicom;F:/github/gdlg'...
GDL> print,getenv('plplot_lib')
C:/usr/plplot5.13.0/lib
GDL> print,getenv('plplot_drv_dir')
C:/usr/plplot5.13.0/drivers
GDL> print,getenv('gdl_path')
+F:/github/gdlgit/src
GDL> pwd
D:/bld/gdl/bld543/install/gdl/bin
GDL> print,getenv('gdl_startup')
D:/home/greg/.gdl_startup
GDL>

Also, just from a CMD.exe shell,

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\cmd>set PATH=F:\github\gdlgit\install\gdl\bin;%PATH%

D:\cmd>gdl

  GDL - GNU Data Language, Version 0.9.8 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

\% Compiled module: PATH_SEP.
 = = = = 
  NOTE: This works because all of the shareable images required by the GDL built are included in the directory that it is located, and this directory is added to the %PATH% variable in front of any others.
 = = = =

 My preferable method of GDL use on windows makes use of the bash shell provided by MSYS2.  MSYS2 is a reduced version of Cygwin, kept near current with the actual Cygwin that allows reference to files as in Linux, i.e. C: drive becomes /c/, D: drive becomes /d/ , and back-slashes are reserved escape characters.  Running GDL this way is similar to running it from a Linux window.  MSYS does not compile GDL, it only provides a shell compatible with the autoconfig/configure methods used in the unix world.  

A small and incomplete MSYS2 installation is still an asset to your windows utilities (as is GDL itself).
On my windows'7 I created a shortcut to CMD.exe and modified it as follows:
Target: C:\msys64\usr\bin\bash.exe -login -i      <--- pointing to the exec for the bash shell
Start in: C:\msys64\usr\bin
the "-i" flag indicates that a shell window is created (until exit command) and the -login invokes execution of initialization routines ~/.bashrc included.
 
My own method of bringing GDL to this MSYS shell is to execute a script called "run32" as distinct from "run64" which is used if 64-bit GDL is to be run. run32 sets up the path and defines the aliases for the various gdl builds I have - each of which are still happy with the single PATH definition using /mingw32/bin;opt32/bin.

**Comment by maynardGK** [comment]
I'll start the problems: confirming on a random windows' 8.1 system that console input is funky. After first failure, which was a security wall (more info .. run anyway) then I got GDL up in a CMD.exe shell (looks like) by a simple explorer click.  But it is not taking input, even though it is reporting its startup conditions.  Similar result when run from windows' powershell.

OK so this problem is answered by replacing readline-7 with readline-6.3 and the new reference build is
https://ci.appveyor.com/api/buildjobs/tcgs0xqu17h7o7jn/artifacts/gdl_build.zip (build 600)
In the process I installed a new msys2 (1-click but add "pacman -S vim tar")
and struggled to get a copy of the CMD.exe program as a shortcut link.  When modified as described above the console worked fine, and it worked when invoked from explorer click.

**Comment by SIAMAR** [comment]
The problems i had with the Appveyor build came from readline-7, using the last Appveyor build from https://github.com/gnudatalanguage/gdl/pull/431 (https://ci.appveyor.com/api/buildjobs/tcgs0xqu17h7o7jn/artifacts/gdl_build.zip) fixed GDL in the CMD.
I still had problems with plplot and did a simple .bat to init the env variables i needed 

```
set plplot_lib=C:\Users\sflinois\Desktop\appveyor-plplot6.3\install\plplot5.13\lib
set plplot_drv_dir=C:\Users\sflinois\Desktop\appveyor-plplot6.3\install\plplot5.13\drivers
gdl.exe
```
readline-6.3 on builds running on windows 8+ seems to work fine (I'm on Windows 10)
I'll test if the build is missing some feature and report it here =)

**Comment by sflinois** [comment]
The problems i had with the Appveyor build came from readline-7, using the last Appveyor build from #431 (https://ci.appveyor.com/api/buildjobs/tcgs0xqu17h7o7jn/artifacts/gdl_build.zip) fixed GDL in the CMD.
I still had problems with plplot and did a simple .bat to init the env variables i needed
set plplot_lib=C:\Users\sflinois\Desktop\appveyor-plplot6.3\install\plplot5.13\lib
set plplot_drv_dir=C:\Users\sflinois\Desktop\appveyor-plplot6.3\install\plplot5.13\drivers
gdl.exe
readline-6.3 on builds running on windows 8+ seems to work fine (I'm on Windows 10)
I'll test if the build is missing some feature and report it here =)

**Comment by maynardGK** [comment]
64-bit GDL can be run from this https://ci.appveyor.com/api/buildjobs/cvln9j3jbes8icng/artifacts/gdl_build.zip

test_xdr causes program crash in an otherwise "successful" 64-bit windows build (see first in matrix): #431 
32-bit version run from home artifact (build 566) completes through banner report, then crashes.

xdr is built from https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/bsd-xdr/bsd-xdr-1.0.0.tar.gz
for x86_64 to compile, the warning disregard flag is used, -Wno-pointer-to-int-cast 
This seems ok because the pointer-to-int calculations appear to be related to alignment issues - the first byte of the address.  Maybe it really is a problem, maybe not.

A debug build of the 32-bit version, which is probably suffering from the same problem, can be downloaded
as https://ci.appveyor.com/api/buildjobs/k1d45xl1x9i0vrqs/artifacts/gdl_build.zip.  The 64-bit debug build is not available due to exceeding a size limit (see log).

**Comment by maynardGK** [comment]
https://ci.appveyor.com/project/slayoo/gdl/builds/20137939 contains the builds for win32 in the current (2018 Nov 7) git.  64-bit does not use Widgets nor graphicsmagick,  and passes testing (test_window_background is the exception). At 32-bits, wxWidgets and GraphicsMagick can be included but the GM libraries are the 8-bit image libraries distributed by msys.org. This build produces the following list of errors:
 The following tests FAILED:
[00:16:48] 	  1 - test_angles.pro (SEGFAULT)
[00:16:48] 	  5 - test_base64.pro (SEGFAULT)
[00:16:48] 	 56 - test_call_procedure.pro (SEGFAULT)
[00:16:48] 	 58 - test_common.pro (SEGFAULT)
[00:16:48] 	 62 - test_erfinv.pro (SEGFAULT)
[00:16:48] 	 78 - test_linfit.pro (SEGFAULT)
[00:16:48] 	 79 - test_modulo.pro (SEGFAULT)
[00:16:48] 	 81 - test_netcdf.pro (Failed)
[00:16:48] 	 86 - test_ptrarr.pro (SEGFAULT)
[00:16:48] 	 94 - test_scope_varfetch.pro (SEGFAULT)
[00:16:48] 	100 - test_trisol.pro (SEGFAULT)

When run at home:
```
alias gdl32='bash -c "export PATH=.:$PATH && /f/github/gdl32/install/gdl/bin/gdl"'
greg@Homerw7  /f/github/gdl32/blds
$ echo $PATH
/c/usr/bin32:/c/usr/bin32/mingw:/c/usr/lib32:/mingw32/bin:/opt32/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/system32:/c/Windows/system32/Wbem
greg@Homerw7  /f/github/gdl32/blds
$ gdl32

  GDL - GNU Data Language, Version 0.9.8 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
GDL> test_angles
% Compiled module: TEST_ANGLES.
% Compiled module: REAL_PART.
% TEST_ANGLES: PASSED
GDL> test_base64
% Compiled module: TEST_BASE64.
GDL> test_call_procedure
% Compiled module: TEST_CALL_PROCEDURE.
% BASIC_CALL_PROCEDURE: testing CALL_PROCEDURE: No
GDL> test_common
% Compiled module: TEST_COMMON.
GDL> test_erfinv
% Compiled module: TEST_ERFINV.
% Compiled module: IMSL_ERF.
GDL> test_linfit
% Compiled module: TEST_LINFIT.
% Compiled module: LINFIT.
% Compiled module: ERRORS_ADD.
% TEST_LINFIT: Error on operation : Unexpected ret
% TEST_LINFIT: ===================================
% TEST_LINFIT: =
% TEST_LINFIT: =  1 errors encountered during TEST
% TEST_LINFIT: =
% TEST_LINFIT: ===================================
GDL> test_modulo
% Compiled module: TEST_MODULO.
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_INTEGERS: NO errors found in MODULO_ON
% MODULO_ON_FLOAT: OK for /Float and NBP= 100, sca
% MODULO_ON_FLOAT: OK for /Double and NBP= 100, sc
% MODULO_ON_FLOAT: OK for /Float and NBP= 1230, sc
% MODULO_ON_FLOAT: OK for /Double and NBP= 1230, s
% MODULO_ON_FLOAT: OK for /Float and NBP= 1230, sc
% MODULO_ON_FLOAT: OK for /Double and NBP= 1230, s
% TEST_MODULO: ===================================
% TEST_MODULO: =
% TEST_MODULO: =  NO errors encountered during TES
% TEST_MODULO: =
% TEST_MODULO: ===================================
GDL> test_netcdf
% Compiled module: TEST_NETCDF.
% TEST_NETCDF: GDL was compiled without NetCDF !

$gdl32
- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patche
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
GDL> test_ptrarr
% Compiled module: TEST_PTRARR.
% Compiled module: DIST.
GDL> test_scope_varfetch
% Compiled module: TEST_SCOPE_VARFETCH.
    1234
% ASTRON_READCOL1: inside
      0.00000      1.00000      2.00000      3.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL1BIS: inside
      0.00000      1.00000      2.00000      3.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL2: inside
      0.00000      1.00000      2.00000      3.00000
      7.00000      8.00000      9.00000
    1234
% ASTRON_READCOL1: inside
      0.00000      1.00000      2.00000      3.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL1BIS: inside
      0.00000      1.00000      2.00000      3.00000
      7.00000      8.00000      9.00000
% ASTRON_READCOL2: inside
      0.00000      1.00000      2.00000      3.00000
      7.00000      8.00000      9.00000
GDL> test_trisol
% Compiled module: TEST_TRISOL.
      -1.0000000       2.0000000       2.0000000      -1.
% Compiled module: DIAG_MATRIX.
% TEST_TRISOL: TRISOL succesfully tested
GDL> exit

greg@Homerw7  /f/github/gdl32/blds
$ export PATH=/c/Windows/system32:/c/Windows/system32/Wbem

greg@Homerw7  /f/github/gdl32/blds
$ gdl32
bash: bash: command not found

greg@Homerw7  /f/github/gdl32/blds
$ export PATH=/usr/local/bin:/usr/bin:/bin:$PATH

greg@Homerw7  /f/github/gdl32/blds
$ gdl32

  GDL - GNU Data Language, Version 0.9.8 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
GDL> test_angles
% Compiled module: TEST_ANGLES.
% Compiled module: REAL_PART.
% TEST_ANGLES: PASSED
GDL> test_ptrarr
% Compiled module: TEST_PTRARR.
% Compiled module: DIST.
GDL>% TEST_MATH_FUNCTION_DIM: =================================
% TEST_MATH_FUNCTION_DIM: =
% TEST_MATH_FUNCTION_DIM: =  NO errors encountered during T
% TEST_MATH_FUNCTION_DIM: =
% TEST_MATH_FUNCTION_DIM: =================================
% TEST_MATH_FUNCTION_DIM: re-run with /verbose for details
GDL> test_matrix_multiply
% Compiled module: TEST_MATRIX_MULTIPLY.
% TEST_MATRIX_MULTIPLY: Types 14 and 15 desactivated due to
% Compiled module: DIAG_MATRIX.
GDL>
```

**Comment by slayoo** [comment]
Closing this one - suggest creating new issues for particular aspects of the windows builds
