### ISSUE TITLE
segfaults introduced in #480

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#484]
Since #480 we have multiple deterministic segfaults on Appveyor:
```
The following tests FAILED:
	 61 - test_deriv.pro (SEGFAULT)
	 67 - test_file_delete.pro (SEGFAULT)
	 75 - test_idl_validname.pro (SEGFAULT)
	 98 - test_standardize.pro (SEGFAULT)
	103 - test_where.pro (SEGFAULT)
Errors while running CTest
```

**Comment by alaingdl** [comment]
This is only for MSwin, isn't ?

I was aware of that, but I need to go ahead to test WHERE() around. (and check again the global figures of benchmarks, which become to be very smart !)

I am quite surprise the changes have such side effect on MSwin, may-be because of few
includes I had to add ... (in includefirst.hpp ?!)

Help or feedback by @maynardGK would be also very welcome (despite having now a smart infrastructure on MSwin, thanks to @SIAMAR , I am not at ease ... but [Remmina](https://remmina.org/) is nice !)

**Comment by maynardGK** [comment]
I suspect most segfaults are not generated by bad code, but by mis-matching libraries. 

here I've re-compiled @64bits win7 at home with the new stuff in as well,
```
$ gdltst

  GDL - GNU Data Language, Version 0.9.8e (/f/gdl )
< verbatim screen dump showing tests passing >
GDL>
```
Now I've hit this in my #478, 32-bit build, no problems like that in the 64-bit build. (using mingw, gcc 6.3)

**Comment by slayoo** [comment]
BTW, it would be great to disable the failing tests for appveyor in such PRs before merging - otherwise master is failing making all other PRs "bad" :(
