### ISSUE TITLE
Linking problem on Mac

### ISSUE THREAD

**Issue by kailenking** [gnudatalanguage/gdl#558]
Hello, 
I am trying to compile gdl on my MacBook but when its linking I get the following error. Does anybody have a suggestion on how to solve this problem?

thanks,
Kailen

[100%] Linking CXX executable gdl
Undefined symbols for architecture x86_64:
  "_history_list", referenced from:
      recall_commands_internal() in gdlhelp.cpp.o
  "_rl_event_hook", referenced from:
      DInterpreter::InterpreterLoop(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in dinterpreter.cpp.o
      InitGDL() in gdl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/gdl] Error 1
make[1]: *** [src/CMakeFiles/gdl.dir/all] Error 2
make: *** [all] Error 2

**Comment by alaingdl** [comment]
yes, for me it is directly related to missing functionnalities in EditLine on OSX.
(and, yes, maybe I am in fault not to have finishing some polishing in the cmake files ...)

because readline (or editline) give a lot to GDL at CLI level,
please consider to compile with readline !

a solution to try is the [minimal script](https://github.com/gnudatalanguage/gdl/blob/master/scripts/minimum_script4gdl.sh) I updated few weeks ago ...

A.

**Comment by slayoo** [comment]
related: #11 ?

**Comment by kailenking** [comment]
Thank you for the suggestions. I made it work using readline and your script. I had to force the script to use my new cmake instead of what it downloaded. So thanks for your help.

Kailen

**Comment by slayoo** [comment]
no more editline (#762), closing
