### ISSUE TITLE
PLplot and xwin

### ISSUE THREAD

**Issue by kailenking** [gnudatalanguage/gdl#563]
Hello again,

GDL is working, but I cannot plot because PLplot appears to not have the xwin driver. 
GDL> window,0
% PLplot installation lacks the requested driver: xwin
% Execution halted at: $MAIN$          
GDL> 

I just installed PLplot using brew on the Mac, and I also tried to compile it myself, but neither helped.
Any suggestions? 
Thank You,
Kailen

**Comment by alaingdl** [comment]
sorry for the delay

unclear for me :(

if it was a Linux (ubuntu), for sure just install a package will be enough
plplot12-driver-xwin

but for OSX and brew, unclear !
I just did  brew info plplot
but no information on xwin

Q1 : did you install Xcode ?
Q2 : did you try to compile with the scripts/minimum_script4gdl.sh ?
(no problem on OSX 10.12 & 10.13, just tested) It does compile what is need for plplot
Then you can link to it for a more complete compilation of GDL
 
to have 0.9.9, in a terminal (CLI) :
```$ ./minimum_script4gdl.sh ```

the line at the end after compilation explains how to launch the code

then, to upgrade into 0.9.9+git, in a terminal (CLI) :
``` $ ./minimum_script4gdl.sh 6 ```

You can also look what you have with otool -L : 
```
otool -L gdl-0.9.9/src/gdl
...
	@rpath/libplplot.15.dylib (compatibility version 15.0.0, current version 15.0.0)
	@rpath/libplplotcxx.13.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/opt/graphicsmagick/lib/libGraphicsMagick.3.dylib (compatibility version 23.0.0, current version 23.0.0)
	/usr/local/opt/graphicsmagick/lib/libGraphicsMagick++.12.dylib (compatibility version 17.0.0, current version 17.0.0)
	/usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libSM.6.dylib (compatibility version 7.0.0, current version 7.1.0)
	/opt/X11/lib/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)

```

**Comment by maynardGK** [comment]
> GDL is working, but I cannot plot because PLplot appears to not have the xwin driver.
> GDL> window,0
> % PLplot installation lacks the requested driver: xwin
> % Execution halted at: $MAIN$
> GDL>
> 
> I just installed PLplot using brew on the Mac, and I also tried to compile it myself, but neither helped.
> Any suggestions?
> Thank You,
> Kailen

( I don't have a Mac to experiment but just to suggest the following:)
From the error message, it appears you have connected with plplot, but that plplot has not found the driver for xwindows, xwin.so or something.  It may have been placed where the link process doesn't search.  If brew has a files-listing for the plplot, look for that, use the find command  (? "find . -name xwin") and place a copy of that file, or a symbolic link to its install location, where gdl is sure to find it (i.e. where it finds libplplot).

You should be able to compile plplot on Mac - use at least version 5.13 and give it a shot, there is a lot of active helpers associated with that package if you fail.  For the purpose of GDL you only need a few options turned on, the cmake I use for this on linux is
````
cmake -DCMAKE_INSTALL_PREFIX=/usr/local  \
-DENABLE_DYNDRIVERS=ON -DDEFAULT_NO_CAIRO_DEVICES=ON -DDEFAULT_NO_QT_DEVICES=ON \
-DDEFAULT_NO_BINDINGS=ON -DENABLE_cxx=ON -DENABLE_wxwidgets=ON -DOLD_WXWIDGETS=ON \
-DWITH_FREETYPE=OFF \
-DPLD_pdf=OFF -DPLD_psttf=OFF \
/f/plplot/plplot-5.13.0
````
The special compile OLD_WXWIDGETS is needed to draw inside widgets.  Since /usr/local will supersede the install location, any other use of plplot will not be properly used, so the install location should be /usr/local/gdl or something (and specified when GDL is built).

**Comment by slayoo** [comment]
Closing as an inactive support-request issue. Please submit a new one if the problem persists

**Comment by kkin1995** [comment]
Same issue occurred for me on macOS Big Sur 11.2
