### ISSUE TITLE
Interpreter issue - "implied print" - used in a compound statement.

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#593]
I was trying to use an implied print after a compound  statement.
````
GDL> orbf=file_search('./','orbit',/dir,count=norb) & print,norb
         857
GDL> orbf=file_search('./','FPorbit_Day*',count=norb) & norb
% PRINT: Keyword parameter <ORBF> not allowed in call to: PRINT
% Execution halted at: $MAIN$
GDL> help,orbf
ORBF            STRING    = Array[857]
````
In the journal file the following is found:
````
orbf=file_search('./','orbit',/dir,count=norb) & print,norb
;         857
print,/implied_print,orbf=file_search('./','FPorbit_Day*',count=norb) & norb
; % PRINT: Keyword parameter <ORBF> not allowed in call to: PRINT
help,orbf
````

**Comment by GillesDuvert** [comment]
Currently implied print is avaible using an ugly patch (probably the ugliest patch ever written) that, yes, has more drawbacks than usefulness.
At the moment it annoys only us.
If this problem is not solved at the time of next release, it is mandatory to remove the implied print support before the release.
