### ISSUE TITLE
1.0RC: resources/maps are not really source files

### ISSUE THREAD

**Issue by olebole** [gnudatalanguage/gdl#675]
The projections under `resources/maps` are taken from https://proj4.org/operations/projections (right?); however they contain a few glitches which makes it difficult to have them in the Debian package:

First, there is no copyright or license info attached. The [github repository](https://github.com/OSGeo/PROJ) puts them under MIT (if not public domain), but some files have an explicit copyrigt (but no license) statement, like: https://github.com/gnudatalanguage/gdl/blob/296da47ed4f2b9d91f567ef45befe37495012857/resource/maps/high/ne_10m_lakes.README.html#L424

Natural Earth itself seems to put them under PD (then, however, a copyright sign is wrong, since PD is actually the absence of copyright). IMO the license and copyright of these files should somehow be documented.

The second issue is related to the HTML pages: they contain Javascript code that does not come with source code. Ofcourse, one could go through the code and try to find out the origin; however: are the HTML files somehow needed by us? Or could we just live without them? I would really prefer to remove them if they are not needed.

**Comment by olebole** [comment]
Additional question: how should these files handled by the packagers? Currently, they are not installed at all. Shall they go into a separate package? What is the relation to the main shared library?
 * unavoidable dependency: GDL will not run without them, (in Debian: `Depends`)
 * strong dependency: GDL will run, but major functionality loss, (in Debian: `Recommends`)
 * weak dependency: GDL provides extended functionality if this is installed, (in Debian: `Suggests`)

**Comment by alaingdl** [comment]
It is great to have mapping in GDL without IDL files.
But for me, mapping should be optional then is a weak dependency, and it is a problem for me the data files are big and are in the git depot. It would be great to have those files is a separate package.

**Comment by GillesDuvert** [comment]
Hi, I was sort of expecting this discussion.

I find essential to have all the map projections + continent contours etc all at once in GDL, but probably all resources/map files + testsuite/test_map2.pro + testsuite/interactive_tests/test*map.pro could be provided in a separate package.

The thing is, everything is tied: one needs the proj library linked in gdl, but also the map*.pro files in lib/. Those in turn provide some options that need the presence of the resouces/map/* files.  So, the dependency is "strong" **as GDL commands will fail if the package is not installed**.

And, I'm particularly opposed to have special code in our procedures to handle the absence of installation of some dependency when this dependecy is in the GDL source code on GH, and the corresponding files have used an incredible amount of time to be written!.

Regarding the files in resources/map , they are mostly taken (as stated in MAP_INSTALL) from NaturalEarth and I've kept all the files in the NE download thinking it was needed to comply with NE's license.

As I understand now, there is no particular license associated and since several files are of no use at all (the .html files and its javascript code) I'll remove them. Basically one eeds only the .dbf, .shx and .shp files ans that's all. So adding a general copyright-keeping text somewhere in the resurces/map directory should be ok? 

The copyright would thus be "2009 - 2018. Natural Earth. All rights reserved." (whatever that means)  for all files except "continents" files that keep the LGPL GSHHG license.

Shall we do like that?
Best
Gilles

**Comment by GillesDuvert** [comment]
@olebole see what comes out of #686

**Comment by olebole** [comment]
Maybe we could make a RC2 release? @slayoo ?

**Comment by slayoo** [comment]
@alaingdl @GillesDuvert @maynardGK Any objections to release RC2 in the coming days?

**Comment by alaingdl** [comment]
No

I did not find a solution for the bug RANDOMN(seed, 1, poisson=4e9,/double)
which is related to a limit in the GSL (as far I as understand)

A.

**Comment by GillesDuvert** [comment]
@acoulais  I do not find the issue related to your problem?
My tests look good (difficult to be sure as the value returned is itself a random value)

**Comment by slayoo** [comment]
@olebole can we close this one?

**Comment by olebole** [comment]
Since the Javascript polluted HTML files are gone, and there is a COPYRIGHT file documenting the license, my concerns are handled well. Thanks. Closing...
