### ISSUE TITLE
colors1.tbl traceback error

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#723]
Copy-pasting issue just created on SourceForge:

```
Created: Thu Feb 27, 2020 06:01 AM UTC by Ajith

Hi,

I'm new to GDL and I'm trying to use an algorithm called FHD and it needs other IDL libraries 
like HEALPix, etc.,

So, while testing installation of FHD, I'm tring to create a random image using this command:

imagefast,randomN(5,256,256),filepath='/home/ajith/testimage.png'

But the result shows this:

% Compiled module: IMAGEFAST.
% Compiled module: CGHASIMAGEMAGICK.
% Compiled module: CGLOADCT.
% Compiled module: FILEPATH.
% Compiled module: STRSPLIT.

Traceback Report from IMAGEFAST:

 Error opening file. Unit: 100, File: /usr/resource/colors/colors1.tbl

*% Compiled module: DIALOGMESSAGE.
% DIALOGMESSAGE: Variable is undefined: ERR
% Execution halted at: DIALOGMESSAGE 262 /home/ajith/workspace/coyote/dialogmessage.pro
% CGLOADCT 200 /home/ajith/workspace/coyote/cgloadct.pro
% IMAGEFAST 155 /home/ajith/workspace/FHD/fhdoutput/imagefast.pro
% $MAIN$ *

Can you help me with this colors1.tbl problem? I couldnt find any file like that in 
my installaion or anywhere in my system.

Thanks in advamce,
Ajith
```

**Comment by GillesDuvert** [comment]
Thank you for the report.
Please report any further problem you'll encounter. In this case it is quite simple:
coyote's cgloadct procedure uses the IDL colortable file and find it with:
` file = Filepath('colors1.tbl', SUBDIRECTORY=['resource', 'colors'])`
which does not exist in the GDL distribution (GDL handle colortables differently+copyrights problems).
You can google for it (it's almost everywhere!), and put it where above `file` says it should be.
Or, just use "loadct" instead of cgloadct in your programs, it's probably sufficient.

The very useful coyote programs (now legacy) should be tweaked to support non-pure-idl environment but this is another story.

**Comment by ajithsampath** [comment]
I downloaded the .tbl file and put it in the directory still its showing the same error.

What should I do?

**Comment by GillesDuvert** [comment]
@ajithkathir unfortunately this "works for me" as I happen to have the file in the right place.
Note that the directory must be exactly the one where cgloadct expects the colortable, i.e., probably something like $IDL_DIR/resource/color/
Again, it is probably unnecessary to use cgloadct instead of loadct in your(?) program.

**Comment by ajithsampath** [comment]
As I said thats not my program I'm trying to run. Its FHD used for imaging in radio astronomy.
And If I change cgloadct to loadct I have to change everything inside the whole package FHD.

**Comment by GillesDuvert** [comment]
@ajithkathir I've installed FHD (sort of) and typed in GDL :
`imagefast,randomN(5,256,256),filepath='/tmp/testimage.png'`
it works.
Since I have the file `colors1.tbl` in `$IDL_DIR/resource/color/` this is not surprising.
I have used gdl-0.9.9 , linux version.
I hope you will get this thing to work. We'll be happy to hear about any error occurring when running FHD with GDL, this is how we can (slowly) improve our product.

**Comment by ajithsampath** [comment]
I have the same gdl-0.9.9, and when I type `echo $IDL_DIR` I couldnt find any output.
The thing is I dont know where this $IDL_DIR is.

**Comment by ajithsampath** [comment]
Hey I found it and its working.
But some other functions are missing, I'll downloading them and put them in the required directory.
If any other error comes up, I'll report you for sure.

Thanks for your time and Thanks a lot for reaching out to help me. :)

**Comment by ajithsampath** [comment]
And now I created that image using `imagefast` command. Thanks again :)
