### ISSUE TITLE
Appveyor builds stopped working 

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#728]
@maynardGK Could you please have a look at the appveyor builds - started to fail with:
```
tar: mingw-w64-x86_64-readline-6.3.008-1-any.pkg.tar.xz: Cannot open: No such file or directory
```
See e.g.:
https://ci.appveyor.com/project/slayoo/gdl/branch/master/job/643no3m7j7hh5ykx

**Comment by maynardGK** [comment]
The repository repo.msys2.org  is not responsive, I can't see what they are doing with it yet.
Using version 6.3 is necessary because of (... ? ...) problems with version 7, gcc 6 or so.  I am however doing ok with version 8 but that is here with gcc 9 - beyond the appveyor versions.
So give it a few days and maybe we get reconstituted repos, there are a lot of other paths requiring repo.msys2.org in the scripts.

**Comment by maynardGK** [comment]
@GillesDuvert I just checked the repository website and it appears to be back up; Appveyor should run again.

**Comment by slayoo** [comment]
works:

![image](https://user-images.githubusercontent.com/89685/76468254-d29a1880-63eb-11ea-915b-cc593e8479f5.png)


Thanks @maynardGK for following up.
