### ISSUE TITLE
GDL oplot option missing y axis

### ISSUE THREAD

**Issue by ghost** [gnudatalanguage/gdl#808]
Using GDL with oplot (multiple plot over plot) I noticed y axis axis omitted.  Generating file is bcalcstix20f_SU1Q.pro .  Also, on x axis tick mark comes down through 0 of plot numbers.  
Not supported yet MAP_SET, which does world plots, and Helvetica. Include files are PoyntFlux, and attan_tot.Straight_Up.txt . Plot files generated from IDL are marked with IDL in title, while those form GDL are similarly marked with GDL in the title. 

[bcalcstix20f_SU1Q.txt](https://github.com/gnudatalanguage/gdl/files/4865953/bcalcstix20f_SU1Q.txt)

[PoyntFlux.1Q.txt](https://github.com/gnudatalanguage/gdl/files/4865778/PoyntFlux.1Q.txt)

[atten_tot.Straight_Up.txt](https://github.com/gnudatalanguage/gdl/files/4865761/atten_tot.Straight_Up.txt)

[5_year_ave, lat=-22, long= 114, m=0,Straight_Up,1Q IDL.pdf](https://github.com/gnudatalanguage/gdl/files/4865958/5_year_ave.lat.-22.long.114.m.0.Straight_Up.1Q.IDL.pdf)

[5_year_ave, lat=-22, long= 114, m=0,Straight_Up,1Q GDL.pdf](https://github.com/gnudatalanguage/gdl/files/4865962/5_year_ave.lat.-22.long.114.m.0.Straight_Up.1Q.GDL.pdf)

**Comment by GillesDuvert** [comment]
Hello @PaulGreninger, I do not see the problem with yaxis as the two pdf files have the same plot, complete with y axis?

Indeed, the out ticks do overlap the labels, **this is a bug** not yet reported I believe. 

GDL produces multi-pages PostScript, so your GDL PDF has 2 figures. You may have a better result using the SVG format instead of the PostScript format (all this depends on the respective qualities of the drivers of the plplot library GDL uses) 

GDL has MAP_SET and in some cases, Helvetica. If GDL was not compiled with the proj library, it does not know about MAP_SET. Helvetica should be avaliable for other outputs than X11 (we lack some test files).

Please note that your PoyntFlux.1Q.txt data file is empty so the above procedures cannot possibly work.

**Comment by GillesDuvert** [comment]
@PaulGreninger [here an example of GDL+MAP_SET ](https://github.com/gnudatalanguage/gdl/issues/721#issuecomment-648028223)

**Comment by ghost** [comment]
Thanks for your reply.  The issue of the y axis missing: This feature did not show up in the post script file, as viewed by Centos postscript viewer.  I could not upload these files in ps format to Get Hub.  When you convert these files to pdf using the program ps2pdf, the y axis now becomes visible.

The file PoyntFlux.1Q.txt is 20.5 MB, so the system probably chocked on the upload. If you give me your personal email address, I will be glad to send this file to you so you can reproduce any problem.

Regarding MAP_SET when I compiled the program using minimum_script4gdl.sh I thought I installed proj, for I gave it commands sudo yum install proj, proj-devel, proj-spsg, proj-nad .  Is there any other file related to proj that I also should have installed to get MAP_SET working?

**Comment by GillesDuvert** [comment]
Actually the axis is there, and would print on a prostscript printer. For some reason it is not visible in soft PS viewers.  The feature is most probably due to the absence of a "device,/close" in the procedure ?
Regarding MAP_SET, I think proj-devel is sufficient. However since GDL's continents etc contours (in resources/map) are in Shapefile format, GDL needs to be linked with shapelib also, I'm not cognizant of the minimum_script4gdl.sh but it's name suggests that it does not give GDL its true power. Thus [my remark]( https://github.com/gnudatalanguage/gdl/issues/803#issuecomment-649334541) . You would need a maximum_script4gdl.sh !

**Comment by alaingdl** [comment]
Minimal_script was just a tool to show to new comers that they can compile the GDL interpreter without pain, then doing basic tests (plot). But it seems that I need to upgrade the tool for recent OS because some flags are missing. It is clearly a very limited subset of what GDL provides (no IM/GM, hdf & hdf5, no netcdf, no eigen3 & FFTw ...)

**Comment by GillesDuvert** [comment]
@PaulGreninger was there a special reason (I remember you were [mentioning using a virtual machine](https://github.com/gnudatalanguage/gdl/issues/803#issuecomment-649828553)) no to install a recent distribution (debian wheezy) with a full-fledged GDL?

**Comment by ghost** [comment]
Thanks for your reply.  Regarding map_set I check for closing the device, and it it there.

       map_set,/cylindrical,/continents,/hires,/noborder,/noerase,position=[0.1,0.1,0.95,0.8]
.
.

     !p.multi = 0
     Device, /Close

Using dropbox https://www.dropbox.com/sh/wecyzo9tf5r4otx/AACLiuiipt-q3AGJ-orhTfJIa?dl=0, DEMETER Data>Driver programs, one can access the file PoyntFlux.1Q, for it is over 10 MB, the limit of GutHib uploads.

You asked me why I wasn't using Debian Wheezy.  Educate me.  I installed VirtualBox on my PC because I didn't have a dedicated Linux machine.  I built this machine to mimic the one I used at Air Force Research Lab.  I installed Centos 7, for it had a Fortran compiler built in, and ps2pdf, a post script to pdf converter.

**Comment by GillesDuvert** [comment]
@PaulGreninger Having the same environment at home and at work is indeed desirable. As a GDL developer I'm not using GDL from a distribution, I just suggested the last debian (it may not be wheezy actually) because it was reported it had all the last features...
...but according to the CentOs site, CentOS 7 has the gdl version 0.9.9 (packages gdl-0.9.9-11.20190915git2870075.el7.x86_64.rpm and  gdl-common-0.9.9-11.20190915git2870075.el7.noarch.rpm) 
compiled with all dependencies including maps. Something you could use I believe.

**Comment by ghost** [comment]
OK, I tried to install the version in Centos 7, but it said it could not find the package:

[pgreninger@localhost ~]$ hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 91bc83aa526f4be9a008eb60407aea4c
           Boot ID: e8fa92c3cc314f4cb00b7f067680717d
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64
[pgreninger@localhost ~]$ sudo yum install gdl-0.9.9-11.20190915git2870075.el7.x86_64.rpm
[sudo] password for pgreninger: 
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.cs.uwp.edu
 * epel: mirrors.xmission.com
 * extras: mirror.oss.ou.edu
 * updates: mirror.cs.uwp.edu
No package gdl-0.9.9-11.20190915git2870075.el7.x86_64.rpm available.
Error: Nothing to do

**Comment by slayoo** [comment]
What does plain ``sudo yum install gdl`` give?

**Comment by ghost** [comment]
It says it is already there:

[pgreninger@localhost ~]$ sudo yum install gdl
[sudo] password for pgreninger: 
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repos-lax.psychz.net
 * epel: mirror.oss.ou.edu
 * extras: mirror.oss.ou.edu
 * updates: mirror.cs.uwp.edu
Package gdl-0.9.9-11.20190915git2870075.el7.x86_64 already installed and latest version
Nothing to do

I had turned to that minimum_script4gdl.sh because I was getting an error like ,"znk8wxWindows7IsShounEv, version wxu 3.0 not defined in file libwx gtk3u core-3.0.so.0 with link time reference."

**Comment by GillesDuvert** [comment]
Hm this is exactly what I feared, an unfunctional packaging, preventing people to use GDL out of the box and forcing user to rebuild by him/her/self... All that silently...
Apparently the error message is due to a [python-wxpython installed library](https://github.com/wxWidgets/Phoenix/issues/982) interfering with the wxgtk3 library used in GDL (and others).
This is not something we can detect at build time and packagers cannot detect also unless they actually run GDL in a realistic user environment.
If it is just a shared library mismatch, you could get rid of it, the cleanest way by removing python-wxpython I believe.

**Comment by ghost** [comment]
Thanks for your reply.  No reference to it in .bashrc.  How do I remove it?

**Comment by GillesDuvert** [comment]
I do not use yum (Mageia Linux uses urpm), so this is purely theoretical: reinstalling wxGTK3-3.0.4-1.el7.x86_64.rpm should overwrite the (possibly faulty) libwx_gtk3u_core-3.0.so.0 which may be the cause of conflicts.
So something like 
`sudo yum reinstall wxGTK3`
may do the job.
But I see that wxPython in CentOS7 is linked with wxGTK2. So the mismatch should not have happened! it is something else.
what do you get when you type

>  ldd \`which gdl\`

**Comment by ghost** [comment]
It say wxGTK3 not available in EPEL release.  Which gdl has a lot of output:

[pgreninger@localhost ~]$ sudo yum reinstall wxGTK3
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repos.lax.layerhost.com
 * epel: mirror.oss.ou.edu
 * extras: centos.den.host-engine.com
 * updates: ftp.osuosl.org
Installed package wxGTK3-3.0.2-15.el7.x86_64 (from epel) not available.
Error: Nothing to do
[pgreninger@localhost ~]$ 
[pgreninger@localhost ~]$ ldd `which gdl`
alias:
ldd: ./alias: No such file or directory
gdl='~/gdl-1.0.0-rc.3/build/src/gdl':
ldd: gdl='~/gdl-1.0.0-rc.3/build/src/gdl': No such file or directory
/home/pgreninger/gdl-1.0.0-rc.3/build/src/gdl:
(.. removed)

**Comment by GillesDuvert** [comment]
my mistake, this is 'your' gdl, the one you have rebuilt using minimum_script4gdl.sh
According to CentOS doc, the "installed" gdl (Package gdl-0.9.9-11.20190915git2870075.el7.x86_64) is in /usr/bin/gdl
so the command should be 
`ldd /usr/bin/gdl`

**Comment by ghost** [comment]
Here is what I get:

[pgreninger@localhost ~]$ ldd /usr/bin/gdl
(...)
	libwx_baseu-3.0.so.0 => /lib64/libwx_baseu-3.0.so.0 (0x00007efc1b642000)
	libwx_gtk3u_core-3.0.so.0 => /lib64/libwx_gtk3u_core-3.0.so.0 (0x00007efc1ae5d000)
	libwx_gtk3u_adv-3.0.so.0 => /lib64/libwx_gtk3u_adv-3.0.so.0 (0x00007efc1aa76000)
(...)

**Comment by GillesDuvert** [comment]
Ok your error message was about a "version wxu 3.0 not defined in file libwx gtk3u core-3.0.so.0 with link time reference."
ldd says that `libwx_gtk3u_core-3.0.so.0` is  `/lib64/libwx_gtk3u_core-3.0.so.0 ` and [CentOS ](https://centos.pkgs.org/7/epel-x86_64/wxGTK3-3.0.4-1.el7.x86_64.rpm.html) says that `/lib64/libwx_gtk3u_core-3.0.so.0 ` is provided by wxGTK3-3.0.4-1.el7.x86_64.rpm
Your Yum message says that the current (installed) version is wxGTK3-3.0.2-15.el7.x86_6 , not quite up-to-date wrt. the repository.  So your CentOS is not, eh, "up-to-date".
so somehow one has to update  wxGTK3 to version 3.0.4 . I would suggest updating everything, using [yum update](https://likegeeks.com/yum-update-command/). Or use a more specific command (as I said, my operating system doe not use Yum so I cannot help you further).
Anyway, if perchance the updated gdl works, you will have to call it with `/bin/gdl `as you have redefined 'gdl' to the one you compiled from scratch.

**Comment by ghost** [comment]
Update seems to conflict with a previous package already installed, mostly with regards to printer and faxes.  Does say that gdl-0.9.9-11 is already installed.  Now if I go to usr/bin and type gdl it still launches 1.0.0 the newer one we installed.  So how to get it to point to the one in usr/bin?

Transaction check error:
  file /usr/share/hplip/data/models from install of hplip-common-3.15.9-5.el7.x86_64 conflicts with file from package hplipfull-3.19.11-0.x86_64
(...)

Error Summary
-------------

[pgreninger@localhost ~]$ install gdl
install: missing destination file operand after ‘gdl’
Try 'install --help' for more information.
[pgreninger@localhost ~]$ sudo yum install gdl
[sudo] password for pgreninger: 
Sorry, try again.
[sudo] password for pgreninger: 
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repos.lax.layerhost.com
 * epel: mirror.oss.ou.edu
 * extras: centos.den.host-engine.com
 * updates: ftp.osuosl.org
Package gdl-0.9.9-11.20190915git2870075.el7.x86_64 already installed and latest version
Nothing to do

**Comment by GillesDuvert** [comment]
no more ideas, except that 'gdl' command points to 1.0.0 **but '/bin/gdl' will lauch the good one**. Whatever your current directory. Not the same as typing 'gdl' in the /bin directory, as 'gdl' [is defined as an alias in your ~/.bashrc ](https://github.com/gnudatalanguage/gdl/issues/803#issuecomment-652601011)

**Comment by ghost** [comment]
Ok, I don't know if this works from any directory, I did this from the home directory /bin/gdl. I get:

[pgreninger@localhost ~]$ /bin/gdl
/bin/gdl: relocation error: /bin/gdl: symbol _ZNK8wxWindow7IsShownEv, version WXU_3.0 not defined in file libwx_gtk3u_core-3.0.so.0 with link time reference
[pgreninger@localhost ~]$

**Comment by GillesDuvert** [comment]
OK so we're back to the beginning, this is a packaging bug.
You, as the user of CentOS should [submit a bug report](https://www.centos.org/).

**Comment by ghost** [comment]
Done!

**Comment by GillesDuvert** [comment]
Excellent!

**Comment by ghost** [comment]
They said it was an elep-release problem, so I reported it on their web site.
