### ISSUE TITLE
SORT has a problem with -NaN in large arrays.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#821]
When sorting a large array with negative NaN values, the results are not correctly sorted. Positive NaN values (`!values.f_nan`)  do behave as expected with the NaN values placed at the end. The following example code shows the problem:
````
inn = long(randomn(seed, 7531)*2048l^2)
a[inn] = !values.f_nan
aa[inn] = !values.f_nan
aa2[inn] = -!values.f_nan

ia = sort(abs(a))
iaa = sort(aa)
iaa2 = sort(aa2)

plot, abs(a[ia])   ; Bad
ans = ''
read, ans, prompt = "Press return to continue"

plot, aa[ia]   ; Bad
ans = ''
read, ans, prompt = "Press return to continue"

plot, abs(a[iaa])  ; Good
ans = ''
read, ans, prompt = "Press return to continue"

plot, aa[iaa]   ; Good
ans = ''
read, ans, prompt = "Press return to continue"

plot, aa2[iaa2]   ; Bad

end
````
I was not able to reproduce this with small arrays (e.g. 20 elements and 1 NaN value).

Hardware:
6-core AMD: "AMD Phenom(tm) II X6 1055T Processor"

Software:
GDL 1.0.0-rc3 on up-to-date Manjaro.

P.S. Should `abs(!values.f_nan)` be `-NaN`?

**Comment by jtappin** [comment]
Oops, a couple of lines missing in the code, here is the correct version:
````
a = randomn(seed, 2048l^2)
aa = abs(a)
aa2 = aa

inn = long(randomu(seed, 7531)*2048l^2)
a[inn] = !values.f_nan
aa[inn] = !values.f_nan
aa2[inn] = -!values.f_nan

ia = sort(abs(a))
iaa = sort(aa)
iaa2 = sort(aa2)

plot, abs(a[ia])
ans = ''
read, ans, prompt = "Press return to continue"

plot, aa[ia]
ans = ''
read, ans, prompt = "Press return to continue"

plot, abs(a[iaa])
ans = ''
read, ans, prompt = "Press return to continue"

plot, aa[iaa]
ans = ''
read, ans, prompt = "Press return to continue"

plot, aa2[iaa2]

end
````

**Comment by GillesDuvert** [comment]
@jtappin thanks, this is tricky.
But
abs(NaN) already has a problem!
```
GDL> a=[!values.f_nan,-!values.f_nan]
GDL> abs(a)
         -NaN          NaN
```

**Comment by GillesDuvert** [comment]
Fortunately, GDL provides a GDL_SORT() undocumented function that permits you to choose between "QUICK", "MERGE", "RADIX", "INSERT" and "AUTO".
You can test that
ia = gdl_sort(abs(a),/quick) or ia = gdl_sort(abs(a),/radix) or ia = gdl_sort(abs(a),/merge) give OK results. (INSERT would  wait forever)

The problem is in the AUTO method that is size adaptive and has a flaw here due to the comparison of which subarray sorted is 'smaller' than the other (in which case sorted subarrays are swapped). Obviously the -NaNs are not well understood in this comparison... 
This is a nice bug!

**Comment by jtappin** [comment]
Thanks for the update. 
I think that for the particular problem that I was working on (finding percentiles of images that contains some NaN values) the easiest option for the time being is to make a temporary array of the finite elements and sort that.

**Comment by GillesDuvert** [comment]
In retrospect the problem lies with the Radix() method that aligns correctly all possible IEEE values:
```
GDL> a=[-!values.f_infinity,0,1,-!values.f_nan] &a=[a,-a]& ia = gdl_sort(a,/Radix) &print,a[ia]
         -NaN         -Inf     -1.00000     -0.00000      0.00000      1.00000          Inf          NaN
IDL> a=[-!values.f_infinity,0,1,-!values.f_nan] &a=[a,-a]& ia = sort(a) &print,a[ia]  ; quicksort would do the same.
         -Inf     -1.00000      0.00000     -0.00000      1.00000          Inf         -NaN          NaN
```
Indeed, as sign bits are signficant, if +Nan is at the very 'positive' end, -Nan should be at the most 'negative' one.
thus Radix() cannot be used for floats and doubles as the sorting rank will not be the one of IDL.

**Comment by GillesDuvert** [comment]
A patch has been proposed today, please test.
