### ISSUE TITLE
WIDGET_CONTROL, BASE_SET_TITLE=

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#838]
The BASE_SET_TITLE option, which is used to set the label on tabs, is not available in GDL. Error message (under linux):

% WIDGET_CONTROL: Keyword parameter <BASE_SET_TITLE> not allowed in call to: WIDGET_CONTROL

**Comment by GillesDuvert** [comment]
@PaddyLeahy yes a number of options are not present in WIGDET_XXXX commands (yet). Would you say BASE_SET_TITLE is mandatory or just ignoring it (ie not throwing an error) would be enough?

**Comment by PaddyLeahy** [comment]
@GillesDuvert It is easy enough to comment out the relevant line of code, which I've just done in my application, so I think just ignoring it is not worth doing (unlike the case for issue #839 where the options have no real effect). In my case I have a large widget program built around tabbed draw widgets and not being able to re-title them would require quite a lot of re-coding, although of course it would be possible. The bigger problem is clearly going to be making the draw widgets work; I haven't posted an issue about that yet because we are still experimenting with drivers.

**Comment by GillesDuvert** [comment]
@PaddyLeahy I am in the process of rewriting the widget code of GDL, because it is only marginally doing what is expected. Unless your "large widget program" is not using any 'tricks', the result with todays GDL will be quite unsatisfactory: padding, scrolling, frames, sizes, text fonts ... will only vaguely work. Resizing will be a problem.
I have obtained good results and there will be a new version proposed as github's "Pull Request" (PR) in (difficult to make a commitment) near future. Hopefully this new version should solve some issues you are struggling with. For example I was not aware of the BASE_SET_TITLE option, but have inserted it now in this version.
I'm happy to hear about other problems such as those about the draw widgets. If you are able to recompile GDL from source code, I can provide the development code in my GH copy of GDL.

**Comment by PaddyLeahy** [comment]
@GillesDuvert:  Yes, I have noticed several of these problems already: padding, resizing, fonts..., I don't use scrolling much but do need it for some components which currently fail for other reasons. I'm glad to hear that you are working on improving the widget code.  GDL has been installed for me by our long-suffering computer manager and I'll have to see if he is up to recompiling your version after spending several days sorting out the dependencies in the main linux branch. The next problem I was going to investigate is that the modal widgets used to collect user input tend to cause seg faults in Magick...

However, I'm really very pleased with progress. As it stands GDL allows my code to run with basic functionality and not noticeably slower than IDL, and obviously work is in progress to iron out a lot of the remaining glitches. This has inspired me to push to getting my code into a releasable state, and I may focus on that for a bit then come back to GDL testing in a month or so.

**Comment by GillesDuvert** [comment]
closed by #882
