### ISSUE TITLE
segmentation fault when calling "contour" on 1000x1000 array

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#851]
I get segmentation fault when calling contour program on a 1000x1000 array:

bash$gdl
      GDL - GNU Data Language, Version 1.0.0-rc.3 git
GDL> num1=1000L & num2=1000L
GDL> a=(indgen(num1*num2))^2 ; the wrapping (indgen instead of findgen) is desired here 
GDL> c=float(reform(a,num1,num2))
GDL> 
GDL> window,1,xsize=num1,ysize=num2
GDL> tv,bytscl(c,-1e5,1e5)
GDL> 
GDL> contour,c,levels=1
Segmentation fault (core dumped)

Happens on Suse 15.1 and Debian.
I am using the latest GDL 

Any ideas?

**Comment by alaingdl** [comment]
reproduced :(

and crash also with levels=2, and also without level indication

too much levels ? too complex ? pb on plplot side ??

**Comment by GillesDuvert** [comment]
crash happens in the plplot library, strangely in setlocale() called from plrestore_locale().
Interestingly, `contour,c,lev=[1,1.1],/FILL` works.
when filling, we call plplot's `shade() `function, instead of the normal `cont()` function.

**Comment by GillesDuvert** [comment]
It's a plplot bug. Please report to them. the contouring function pldrawcn() is reentrant, and crashes on your example, probably due to a logic bug in pldrawcn().
I do not see any 'safe' way to avoid that inside GDL, one cannot trap such external libraries bugs.
hopefully we'll use another (faster if possible) contouring algorithm in the future.
```
==8868== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==8868== Can't extend stack to 0x1ffe801098 during signal delivery for thread 1:
==8868==   too small or bad protection modes
```
