### ISSUE TITLE
Fails to build with PROJ 8.0.0

### ISSUE THREAD

**Issue by sebastic** [gnudatalanguage/gdl#893]
PROJ 8.0.0 has removed `proj_api.h` causing `CMakeModules/FindLibproj4new.cmake` to fail:
```
 -- Could NOT find LIBPROJ4 (missing: LIBPROJ4_LIBRARIES LIBPROJ4_INCLUDE_DIR)
```
`src/projections.hpp` needs to be ported to use `proj.h`.

See also: https://proj.org/usage/differences.html

**Comment by GillesDuvert** [comment]
Many thanks,
This was bound to happen one day...
I note it is not mentioned (yet?) in the link you sent.
Are you in position to test that using `proj.h` instead of `proj_api.h` in `src/projections.hpp ` solves the problem?
More generally, we (I at least, as I wrote it) are interested in returns about the map support in GDL since the rewrite of Aprl 2019.

**Comment by sebastic** [comment]
One of the maintainers of the gnudatalanguage package in Debian (e.g. @olebole) should be able to test such changes better than me, but I can see what I can do in that respect as the maintainer of the proj package in Debian.

If you need help porting to the new PROJ API, the [proj mailinglist](https://lists.osgeo.org/mailman/listinfo/proj) is a good venue.

Just replacing `proj_api.h` with `proj.h` won't suffice, refer to the migration documentation for details:

 https://proj.org/development/migration.html

**Comment by GillesDuvert** [comment]
hm, some work indeed. Thanks.

**Comment by opoplawski** [comment]
FWIW - We're hoping to get 8.0.0 into Fedora soon.

**Comment by GillesDuvert** [comment]
Thanks Orion, I do not see anybody working on this small patch and I do not have time for that either.
We are going to have a big release anytime now, plot and widget oriented, it would be a pity the projections were not available.
