### ISSUE TITLE
Weaknesses of GDL on Windows

### ISSUE THREAD

**Issue by eloirozier** [gnudatalanguage/gdl#954]
Here I post a list of some problems encountered while trying to install GDL on windows using the `nightly builds`. I tried to make it as plain as possible.

First, a **general remark**:

 - The artifacts can't be downloaded if you are not logged on to Github. Suggestion : it would also be clearer if there was a specific page listing all of the installers and builds, along with their respective download links, available to both users and non-users of Github.

**Concerning windows installations:**

 - After testing all three types of builds (mini, full_msmpi & full) on a Windows7 machine and a Windows10 machine (both x86_64), it appears that **only the mini version works**.
 -  **The full_msmpi** version (even after installing msmpi) does not crash, but when launched it **stays in background and no window appears...**  (same if called from command line). Is this behaviour normal, or a defect ?
 - As for **the full version, it does as the full_msmpi version, it stays in background.**

I dont know if those are real errors or if it comes from my bad understanding of how the full versions work on windows.

Short remark:
 - At least for windows, builds and installers do not contain the testsuite folder, which is in no way fatal but is not very practical for many reasons (no benchmarks, etc...)

Otherwise everything seems to work normally on windows. I also have questions, with respect to the mini version: does it use Eigen for matrices or not ? Which libraries lack that the full version is supposed to have ? I ask this because benchmarks on this version give quite slow results. Thanks in advance.

**Comment by brandy125** [comment]
I agree that there should be a page with a list of how to install on different systems. It must not be complete but should serve as a starting point for the user.
I am quite sure that many users start to install, encounter a little problem and give up because they do not know how to ask for help.
If there is a page with instructions on how to install on specific operating systems they will give it a try.

**Comment by alaingdl** [comment]
We do have a draft here https://github.com/gnudatalanguage/gdl/wiki but we have the problem only few can modify those pages

**Comment by slayoo** [comment]
> I also have questions, with respect to the mini version: does it use Eigen for matrices or not ? Which libraries lack that the full version is supposed to have ? I ask this because benchmarks on this version give quite slow results. 

IIUC, the windows artefacts are only being built in Debug mode which is not tuned for performance - this is likely worth changing so that Release builds are actually offered.

**Comment by alaingdl** [comment]
Concerning what third party libs. compiled with, in fact I mention to @eloirozier than 
```
GDL> gdl_status
```
will answer ... (without details, nevertheless useful)

**Comment by pjb7687** [comment]
Hi all,

Thanks for the nice comments! Here I would like to explain the current build strategy. For some time ago, we only had a single build pipeline initiated by every commit which generates binaries for every target (debug and release) and every architecture. I thought this is quite inefficient because usually debug builds are sufficient to fix errors in the latest commits.

Therefore, I initiated a discussion here: #925.

And my bad, I just realized that I didn't explain the change I made properly in discussion #925, sorry for that, I thought I already left a proper comment there...

In short, the change that I have introduced is basically we maintain two build pipelines: (1) debug builds, (2) weekly builds.

The former ones (debug builds) are initiated by every commit to the master branch or to any pull request, to quickly check whether the changes make any problem with the builds.

The latter ones (weekly builds) are automatically initiated once a week, generating the release builds + submits a Codecov report. You can see the 'scheduled' builds in the Actions tab. For example, the last successful build seems to be this one: https://github.com/gnudatalanguage/gdl/actions/runs/829874366

By doing that, I thought the number of builds per commit could be reduced, and also we regularly build release build once a week, which would be great to achieve faster build time + of course better for the environment. If you have any comments or thoughts, would be nice to leave your comments to discussion #925.

And now I understand the confusing point - I didn't know that the artifacts are not shown to the users who did not log in. Perhaps I can additionally publish the release build artifacts of the weekly builds to the 'Releases' tab (of course marking that this is a pre-release), and this should be visible to everyone. Would that sound okay? Or any other suggestions are welcome.

**Comment by pjb7687** [comment]
@eloirozier Thanks for the report regarding the full GDL doesn't work on Windows. I can reproduce the same issue. I think I can start working on it this weekend.

**Comment by slayoo** [comment]
> Perhaps I can additionally publish the release build artifacts of the weekly builds to the 'Releases' tab (of course marking that this is a pre-release), and this should be visible to everyone. Would that sound okay?

+1

**Comment by GillesDuvert** [comment]
I tested this morning the full-msmpi installer of the last build  #957 and gdl works with the gdlde, but not when called from the command terminal. (???)

**Comment by pjb7687** [comment]
> I tested this morning the full-msmpi installer of the last build #957 and gdl works with the gdlde, but not when called from the command terminal. (???)

This happens when the wxWidgets 'magic' patch (https://github.com/gnudatalanguage/gdl/blob/master/.ci/build_gdl.sh#L189) didn't work out. I will check it later..

**Comment by pjb7687** [comment]
I found that somehow the 'magic' wxwidgets patch did not work in the past cache. I have rebuilt the build cache and now it seems to work fine. Please reopen if you have the same problem again.

**Comment by pjb7687** [comment]
Regarding testsuite: It seems Linux installation via `apt` also lacks the testsuite directory. But personally, I think it makes sense to omit this since the testsuites are only useful for developers, not the rest of the end-users.

In any case, I think we can discuss this in a new discussion or a new issue thread.

**Comment by GillesDuvert** [comment]
compilation on windows takes extremely long time. See by comparing linux (3min) and windows(16 min) GDL compilation. for builds.

**Comment by eloirozier** [comment]
The last windows full-msmpi works perfectly on a Win10 machine.
